// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package schema

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources with enhanced semantic comparison for schema-specific fields.
//
// This implementation provides:
// - Immutable field detection (SchemaName, DataFormat, RegistryRef)
// - Semantic schema definition comparison
// - Status field tracking for reconciliation
// - Version metadata comparison
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	// Compare immutable fields - these should never change after creation
	// If they do change, it indicates a user error or misconfiguration
	compareImmutableFields(delta, a, b)

	// Compare mutable spec fields
	compareMutableSpecFields(delta, a, b)

	// Compare status fields to determine if reconciliation is needed
	compareStatusFields(delta, a, b)

	// Compare tags
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}

// compareImmutableFields compares fields that should never change after creation
func compareImmutableFields(
	delta *ackcompare.Delta,
	a *resource,
	b *resource,
) {
	// SchemaName is immutable

	if ackcompare.HasNilDifference(a.ko.Spec.SchemaName, b.ko.Spec.SchemaName) {
		delta.Add("Spec.SchemaName", a.ko.Spec.SchemaName, b.ko.Spec.SchemaName)
	} else if a.ko.Spec.SchemaName != nil && b.ko.Spec.SchemaName != nil {
		if *a.ko.Spec.SchemaName != *b.ko.Spec.SchemaName {
			delta.Add("Spec.SchemaName", a.ko.Spec.SchemaName, b.ko.Spec.SchemaName)
		}
	}

	// DataFormat is immutable
	if ackcompare.HasNilDifference(a.ko.Spec.DataFormat, b.ko.Spec.DataFormat) {
		delta.Add("Spec.DataFormat", a.ko.Spec.DataFormat, b.ko.Spec.DataFormat)
	} else if a.ko.Spec.DataFormat != nil && b.ko.Spec.DataFormat != nil {
		if *a.ko.Spec.DataFormat != *b.ko.Spec.DataFormat {
			delta.Add("Spec.DataFormat", a.ko.Spec.DataFormat, b.ko.Spec.DataFormat)
		}
	}

	// RegistryRef is immutable
	if ackcompare.HasNilDifference(a.ko.Spec.RegistryRef, b.ko.Spec.RegistryRef) {
		delta.Add("Spec.RegistryRef", a.ko.Spec.RegistryRef, b.ko.Spec.RegistryRef)
	} else if a.ko.Spec.RegistryRef != nil && b.ko.Spec.RegistryRef != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.RegistryRef.Name, b.ko.Spec.RegistryRef.Name) {
			delta.Add("Spec.RegistryRef.Name", a.ko.Spec.RegistryRef.Name, b.ko.Spec.RegistryRef.Name)
		} else if a.ko.Spec.RegistryRef.Name != nil && b.ko.Spec.RegistryRef.Name != nil {
			if *a.ko.Spec.RegistryRef.Name != *b.ko.Spec.RegistryRef.Name {
				delta.Add("Spec.RegistryRef.Name", a.ko.Spec.RegistryRef.Name, b.ko.Spec.RegistryRef.Name)
			}
		}
	}
}

// compareMutableSpecFields compares fields that can be updated after creation
func compareMutableSpecFields(
	delta *ackcompare.Delta,
	a *resource,
	b *resource,
) {
	// SchemaDefinition changes trigger new version creation
	// We use simple string comparison since semantic validation happens elsewhere
	if ackcompare.HasNilDifference(a.ko.Spec.SchemaDefinition, b.ko.Spec.SchemaDefinition) {
		delta.Add("Spec.SchemaDefinition", a.ko.Spec.SchemaDefinition, b.ko.Spec.SchemaDefinition)
	} else if a.ko.Spec.SchemaDefinition != nil && b.ko.Spec.SchemaDefinition != nil {
		if *a.ko.Spec.SchemaDefinition != *b.ko.Spec.SchemaDefinition {
			delta.Add("Spec.SchemaDefinition", a.ko.Spec.SchemaDefinition, b.ko.Spec.SchemaDefinition)
		}
	}

	// Description is mutable
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}

	// Compatibility mode is mutable
	if ackcompare.HasNilDifference(a.ko.Spec.Compatibility, b.ko.Spec.Compatibility) {
		delta.Add("Spec.Compatibility", a.ko.Spec.Compatibility, b.ko.Spec.Compatibility)
	} else if a.ko.Spec.Compatibility != nil && b.ko.Spec.Compatibility != nil {
		if *a.ko.Spec.Compatibility != *b.ko.Spec.Compatibility {
			delta.Add("Spec.Compatibility", a.ko.Spec.Compatibility, b.ko.Spec.Compatibility)
		}
	}

	// DeletionPolicy is mutable (though changes only affect future deletions)
	if ackcompare.HasNilDifference(a.ko.Spec.DeletionPolicy, b.ko.Spec.DeletionPolicy) {
		delta.Add("Spec.DeletionPolicy", a.ko.Spec.DeletionPolicy, b.ko.Spec.DeletionPolicy)
	} else if a.ko.Spec.DeletionPolicy != nil && b.ko.Spec.DeletionPolicy != nil {
		if *a.ko.Spec.DeletionPolicy != *b.ko.Spec.DeletionPolicy {
			delta.Add("Spec.DeletionPolicy", a.ko.Spec.DeletionPolicy, b.ko.Spec.DeletionPolicy)
		}
	}
}

// compareStatusFields compares status fields to track AWS state changes
// These comparisons help determine if a full reconciliation is needed
func compareStatusFields(
	delta *ackcompare.Delta,
	a *resource,
	b *resource,
) {
	// Compare resolved RegistryARN
	if ackcompare.HasNilDifference(a.ko.Status.RegistryARN, b.ko.Status.RegistryARN) {
		delta.Add("Status.RegistryARN", a.ko.Status.RegistryARN, b.ko.Status.RegistryARN)
	} else if a.ko.Status.RegistryARN != nil && b.ko.Status.RegistryARN != nil {
		if *a.ko.Status.RegistryARN != *b.ko.Status.RegistryARN {
			delta.Add("Status.RegistryARN", a.ko.Status.RegistryARN, b.ko.Status.RegistryARN)
		}
	}

	// Compare SchemaARN
	if ackcompare.HasNilDifference(a.ko.Status.SchemaARN, b.ko.Status.SchemaARN) {
		delta.Add("Status.SchemaARN", a.ko.Status.SchemaARN, b.ko.Status.SchemaARN)
	} else if a.ko.Status.SchemaARN != nil && b.ko.Status.SchemaARN != nil {
		if *a.ko.Status.SchemaARN != *b.ko.Status.SchemaARN {
			delta.Add("Status.SchemaARN", a.ko.Status.SchemaARN, b.ko.Status.SchemaARN)
		}
	}

	// Compare LatestVersion metadata
	compareVersionMetadata(delta, a, b)
}

// compareVersionMetadata compares schema version metadata
func compareVersionMetadata(
	delta *ackcompare.Delta,
	a *resource,
	b *resource,
) {
	aVersion := a.ko.Status.LatestVersion
	bVersion := b.ko.Status.LatestVersion

	// Check if one is nil and the other isn't
	if ackcompare.HasNilDifference(aVersion, bVersion) {
		delta.Add("Status.LatestVersion", aVersion, bVersion)
		return
	}

	// If both are nil, no difference
	if aVersion == nil && bVersion == nil {
		return
	}

	// Compare version numbers
	if ackcompare.HasNilDifference(aVersion.VersionNumber, bVersion.VersionNumber) {
		delta.Add("Status.LatestVersion.VersionNumber", aVersion.VersionNumber, bVersion.VersionNumber)
	} else if aVersion.VersionNumber != nil && bVersion.VersionNumber != nil {
		if *aVersion.VersionNumber != *bVersion.VersionNumber {
			delta.Add("Status.LatestVersion.VersionNumber", aVersion.VersionNumber, bVersion.VersionNumber)
		}
	}

	// Compare schema version IDs
	if ackcompare.HasNilDifference(aVersion.SchemaVersionID, bVersion.SchemaVersionID) {
		delta.Add("Status.LatestVersion.SchemaVersionID", aVersion.SchemaVersionID, bVersion.SchemaVersionID)
	} else if aVersion.SchemaVersionID != nil && bVersion.SchemaVersionID != nil {
		if *aVersion.SchemaVersionID != *bVersion.SchemaVersionID {
			delta.Add("Status.LatestVersion.SchemaVersionID", aVersion.SchemaVersionID, bVersion.SchemaVersionID)
		}
	}

	// Compare version status
	if ackcompare.HasNilDifference(aVersion.Status, bVersion.Status) {
		delta.Add("Status.LatestVersion.Status", aVersion.Status, bVersion.Status)
	} else if aVersion.Status != nil && bVersion.Status != nil {
		if *aVersion.Status != *bVersion.Status {
			delta.Add("Status.LatestVersion.Status", aVersion.Status, bVersion.Status)
		}
	}
}
