// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package schema

import (
	"context"
	"fmt"

	ackerrors "github.com/aws-controllers-k8s/runtime/pkg/errors"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	svcapitypes "github.com/aws-controllers-k8s/glue-controller/apis/v1alpha1"
)

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	// Clear the resolved Registry ARN from Status
	// This forces re-resolution on the next reconciliation
	ko.Status.RegistryARN = nil

	return &resource{ko}
}

// HasReferences returns true if the resource has any reference fields set
func (rm *resourceManager) HasReferences(res acktypes.AWSResource) bool {
	ko := rm.concreteResource(res).ko
	return ko.Spec.RegistryRef != nil && ko.Spec.RegistryRef.Name != nil
}

// IsReferenceResolved returns true if all reference fields have been resolved
func (rm *resourceManager) IsReferenceResolved(res acktypes.AWSResource) bool {
	ko := rm.concreteResource(res).ko

	// If there's no reference, it's trivially resolved
	if !rm.HasReferences(res) {
		return true
	}

	// Check if the Registry ARN has been resolved
	return ko.Status.RegistryARN != nil && *ko.Status.RegistryARN != ""
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko.DeepCopy()
	resourceHasReferences := false

	// Resolve RegistryRef if present
	if ko.Spec.RegistryRef != nil && ko.Spec.RegistryRef.Name != nil {
		resourceHasReferences = true

		resolved, err := rm.resolveRegistryReference(ctx, apiReader, ko)
		if err != nil {
			return nil, resourceHasReferences, err
		}
		ko = resolved
	}

	return &resource{ko}, resourceHasReferences, nil
}

// resolveRegistryReference resolves the RegistryRef to a concrete Registry ARN
func (rm *resourceManager) resolveRegistryReference(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.Schema,
) (*svcapitypes.Schema, error) {
	if ko.Spec.RegistryRef == nil || ko.Spec.RegistryRef.Name == nil {
		return ko, nil
	}

	registryName := *ko.Spec.RegistryRef.Name
	namespace := ko.ObjectMeta.Namespace

	// Look up the Registry CRD in the same namespace
	registry := &svcapitypes.Registry{}
	registryKey := types.NamespacedName{
		Namespace: namespace,
		Name:      registryName,
	}

	if err := apiReader.Get(ctx, registryKey, registry); err != nil {
		// If the Registry CRD doesn't exist, this is a terminal error
		// The user needs to create the Registry first
		return nil, ackerrors.NewTerminalError(
			fmt.Errorf("referenced Registry %s/%s not found: %v. Please create the Registry resource first",
				namespace, registryName, err))
	}

	// Validate that the Registry is in a valid state for referencing
	if err := rm.validateRegistryForReference(registry, namespace, registryName); err != nil {
		return nil, err
	}

	// Extract the Registry ARN
	registryARN := string(*registry.Status.ACKResourceMetadata.ARN)

	// Store the resolved Registry ARN in the Status
	// This will be used by SDK operations to construct the registry identifier
	ko.Status.RegistryARN = &registryARN

	return ko, nil
}

// validateRegistryForReference validates that a referenced Registry is in a
// state suitable for being referenced by a Schema
func (rm *resourceManager) validateRegistryForReference(
	registry *svcapitypes.Registry,
	namespace string,
	registryName string,
) error {
	// Check if Registry has ACKResourceMetadata
	if registry.Status.ACKResourceMetadata == nil {
		// This is not terminal - the Registry might still be creating
		// Return a regular error which will cause automatic requeue
		return fmt.Errorf("referenced Registry %s/%s is not ready yet (no metadata)",
			namespace, registryName)
	}

	// Check if Registry has been created in AWS (has an ARN)
	if registry.Status.ACKResourceMetadata.ARN == nil {
		// This is not terminal - the Registry might still be creating
		// Return a regular error which will cause automatic requeue
		return fmt.Errorf("referenced Registry %s/%s is not ready yet (no ARN assigned)",
			namespace, registryName)
	}

	// Validate Registry ARN format
	arn := string(*registry.Status.ACKResourceMetadata.ARN)
	if arn == "" {
		return ackerrors.NewTerminalError(
			fmt.Errorf("referenced Registry %s/%s has an empty ARN",
				namespace, registryName))
	}

	// Check if Registry is in a terminal error state
	if registry.Status.Conditions != nil {
		for _, condition := range registry.Status.Conditions {
			if condition.Type == "ACK.Terminal" && condition.Status == "True" {
				return ackerrors.NewTerminalError(
					fmt.Errorf("referenced Registry %s/%s is in a terminal error state: %s",
						namespace, registryName, *condition.Message))
			}
		}
	}

	// Check if Registry is being deleted
	if registry.ObjectMeta.DeletionTimestamp != nil {
		return ackerrors.NewTerminalError(
			fmt.Errorf("referenced Registry %s/%s is being deleted and cannot be referenced",
				namespace, registryName))
	}

	return nil
}

// GetRegistryARNFromReference is a helper function to get the Registry ARN
// from either the resolved status or by looking up the reference
func (rm *resourceManager) GetRegistryARNFromReference(
	ctx context.Context,
	apiReader client.Reader,
	schema *svcapitypes.Schema,
) (string, error) {
	// If already resolved in status, return it
	if schema.Status.RegistryARN != nil && *schema.Status.RegistryARN != "" {
		return *schema.Status.RegistryARN, nil
	}

	// If no RegistryRef specified, use default registry
	if schema.Spec.RegistryRef == nil || schema.Spec.RegistryRef.Name == nil {
		// AWS Glue uses a default registry, we return empty string to indicate default
		return "", nil
	}

	// Resolve the reference
	resolved, err := rm.resolveRegistryReference(ctx, apiReader, schema)
	if err != nil {
		return "", err
	}

	if resolved.Status.RegistryARN == nil {
		return "", fmt.Errorf("failed to resolve Registry ARN")
	}

	return *resolved.Status.RegistryARN, nil
}
