// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package schema

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/glue"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/glue/types"
	smithy "github.com/aws/smithy-go"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/glue-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Schema{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = fmt.Sprintf("")
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()

	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetSchemaOutput
	resp, err = rm.sdkapi.GetSchema(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetSchema", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "EntityNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.SchemaName != nil {
		ko.Spec.SchemaName = resp.SchemaName
	} else {
		ko.Spec.SchemaName = nil
	}

	if resp.SchemaArn != nil {
		if ko.Status.ACKResourceMetadata == nil {
			ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
		}
		tmpARN := ackv1alpha1.AWSResourceName(*resp.SchemaArn)
		ko.Status.ACKResourceMetadata.ARN = &tmpARN
		ko.Status.SchemaARN = resp.SchemaArn
	}

	if resp.RegistryArn != nil {
		ko.Status.RegistryARN = resp.RegistryArn
	}

	if resp.DataFormat != "" {
		dataFormat := string(resp.DataFormat)
		ko.Spec.DataFormat = &dataFormat
	}

	if resp.Compatibility != "" {
		compat := string(resp.Compatibility)
		ko.Spec.Compatibility = &compat
	}

	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	}

	// Set the latest schema version metadata
	if resp.LatestSchemaVersion != nil || resp.SchemaStatus != "" {
		latestVersion := &svcapitypes.SchemaVersionMetadata{}

		if resp.LatestSchemaVersion != nil {
			latestVersion.VersionNumber = resp.LatestSchemaVersion
		}

		if resp.SchemaStatus != "" {
			status := string(resp.SchemaStatus)
			latestVersion.Status = &status
		}

		if resp.CreatedTime != nil {
			// CreatedTime is a string in ISO 8601 format, parse it
			if parsedTime, err := time.Parse(time.RFC3339, *resp.CreatedTime); err == nil {
				createdTime := metav1.NewTime(parsedTime)
				latestVersion.CreatedTime = &createdTime
			}
		}

		ko.Status.LatestVersion = latestVersion
	}

	rm.setStatusDefaults(ko)

	latest = &resource{ko}
	return latest, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.SchemaName == nil
}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetSchemaInput, error) {
	res := &svcsdk.GetSchemaInput{}

	// Build SchemaId from the resource
	schemaId := &svcsdktypes.SchemaId{}

	if r.ko.Spec.SchemaName != nil {
		schemaId.SchemaName = r.ko.Spec.SchemaName
	}

	// Use Registry ARN from status if available (populated by ResolveReferences)
	if r.ko.Status.RegistryARN != nil {
		// For GetSchema, we need to use the registry ARN in the SchemaId
		// AWS accepts registry name in SchemaId even though there's a separate RegistryId parameter
		schemaId.RegistryName = r.ko.Status.RegistryARN
	} else if r.ko.Spec.RegistryRef != nil && r.ko.Spec.RegistryRef.Name != nil {
		// Use registry name from reference (will be resolved by ResolveReferences)
		schemaId.RegistryName = r.ko.Spec.RegistryRef.Name
	}

	res.SchemaId = schemaId

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()

	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateSchemaOutput
	_ = resp
	resp, err = rm.sdkapi.CreateSchema(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateSchema", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.SchemaName != nil {
		ko.Spec.SchemaName = resp.SchemaName
	} else {
		ko.Spec.SchemaName = nil
	}
	if resp.SchemaArn != nil {
		if ko.Status.ACKResourceMetadata == nil {
			ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
		}
		tmpARN := ackv1alpha1.AWSResourceName(*resp.SchemaArn)
		ko.Status.ACKResourceMetadata.ARN = &tmpARN
		ko.Status.SchemaARN = resp.SchemaArn
	}
	if resp.RegistryArn != nil {
		ko.Status.RegistryARN = resp.RegistryArn
	}
	if resp.DataFormat != "" {
		dataFormat := string(resp.DataFormat)
		ko.Spec.DataFormat = &dataFormat
	}
	if resp.Compatibility != "" {
		compat := string(resp.Compatibility)
		ko.Spec.Compatibility = &compat
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	}
	if resp.LatestSchemaVersion != nil || resp.SchemaStatus != "" {
		latestVersion := &svcapitypes.SchemaVersionMetadata{}

		if resp.LatestSchemaVersion != nil {
			latestVersion.VersionNumber = resp.LatestSchemaVersion
		}

		if resp.SchemaStatus != "" {
			status := string(resp.SchemaStatus)
			latestVersion.Status = &status
		}

		ko.Status.LatestVersion = latestVersion
	}

	rm.setStatusDefaults(ko)

	created = &resource{ko}
	return created, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateSchemaInput, error) {
	res := &svcsdk.CreateSchemaInput{}

	if r.ko.Spec.SchemaName != nil {
		res.SchemaName = r.ko.Spec.SchemaName
	}
	if r.ko.Spec.SchemaDefinition != nil {
		res.SchemaDefinition = r.ko.Spec.SchemaDefinition
	}
	if r.ko.Spec.DataFormat != nil {
		dataFormat := svcsdktypes.DataFormat(*r.ko.Spec.DataFormat)
		res.DataFormat = dataFormat
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.Compatibility != nil {
		compat := svcsdktypes.Compatibility(*r.ko.Spec.Compatibility)
		res.Compatibility = compat
	}

	// Handle Registry reference
	if r.ko.Status.RegistryARN != nil {
		res.RegistryId = &svcsdktypes.RegistryId{
			RegistryArn: r.ko.Status.RegistryARN,
		}
	}

	if r.ko.Spec.Tags != nil {
		f2 := map[string]string{}
		for f2key, f2valptr := range r.ko.Spec.Tags {
			var f2val string
			if f2valptr != nil {
				f2val = *f2valptr
			}
			f2[f2key] = f2val
		}
		res.Tags = f2
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()

	// Check if SchemaDefinition changed - requires RegisterSchemaVersion
	if delta.DifferentAt("Spec.SchemaDefinition") {
		if err := rm.registerNewSchemaVersion(ctx, desired); err != nil {
			return nil, err
		}
	}

	// Check if Compatibility or Description changed - requires UpdateSchema
	if delta.DifferentAt("Spec.Compatibility") || delta.DifferentAt("Spec.Description") {
		input, err := rm.newUpdateRequestPayload(ctx, desired)
		if err != nil {
			return nil, err
		}

		var resp *svcsdk.UpdateSchemaOutput
		_ = resp
		resp, err = rm.sdkapi.UpdateSchema(ctx, input)
		rm.metrics.RecordAPICall("UPDATE", "UpdateSchema", err)
		if err != nil {
			return nil, err
		}
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)

	updated = &resource{ko}
	return updated, nil
}

// registerNewSchemaVersion registers a new version of the schema when the
// SchemaDefinition changes
func (rm *resourceManager) registerNewSchemaVersion(
	ctx context.Context,
	r *resource,
) error {
	input := &svcsdk.RegisterSchemaVersionInput{}

	schemaId := &svcsdktypes.SchemaId{}
	if r.ko.Spec.SchemaName != nil {
		schemaId.SchemaName = r.ko.Spec.SchemaName
	}
	if r.ko.Status.RegistryARN != nil {
		schemaId.RegistryName = r.ko.Status.RegistryARN
	}
	input.SchemaId = schemaId

	if r.ko.Spec.SchemaDefinition != nil {
		input.SchemaDefinition = r.ko.Spec.SchemaDefinition
	}

	_, err := rm.sdkapi.RegisterSchemaVersion(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "RegisterSchemaVersion", err)
	return err
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.UpdateSchemaInput, error) {
	res := &svcsdk.UpdateSchemaInput{}

	schemaId := &svcsdktypes.SchemaId{}
	if r.ko.Spec.SchemaName != nil {
		schemaId.SchemaName = r.ko.Spec.SchemaName
	}
	if r.ko.Status.RegistryARN != nil {
		schemaId.RegistryName = r.ko.Status.RegistryARN
	}
	res.SchemaId = schemaId

	if r.ko.Spec.Compatibility != nil {
		compat := svcsdktypes.Compatibility(*r.ko.Spec.Compatibility)
		res.Compatibility = compat
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteSchemaOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteSchema(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteSchema", err)
	if err != nil {
		return nil, err
	}

	return nil, nil
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteSchemaInput, error) {
	res := &svcsdk.DeleteSchemaInput{}

	schemaId := &svcsdktypes.SchemaId{}
	if r.ko.Spec.SchemaName != nil {
		schemaId.SchemaName = r.ko.Spec.SchemaName
	}
	if r.ko.Status.RegistryARN != nil {
		registryId := &svcsdktypes.RegistryId{
			RegistryArn: r.ko.Status.RegistryARN,
		}
		_ = registryId
	}
	res.SchemaId = schemaId

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Schema,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}
