// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package database

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/glue"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/glue/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/glue-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Database{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetDatabaseOutput
	resp, err = rm.sdkapi.GetDatabase(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetDatabase", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "EntityNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Database.CatalogId != nil {
		ko.Spec.CatalogID = resp.Database.CatalogId
	} else {
		ko.Spec.CatalogID = nil
	}
	if resp.Database.CreateTableDefaultPermissions != nil {
		f1 := []*svcapitypes.PrincipalPermissions{}
		for _, f1iter := range resp.Database.CreateTableDefaultPermissions {
			f1elem := &svcapitypes.PrincipalPermissions{}
			if f1iter.Permissions != nil {
				f1elemf0 := []*string{}
				for _, f1elemf0iter := range f1iter.Permissions {
					var f1elemf0elem *string
					f1elemf0elem = aws.String(string(f1elemf0iter))
					f1elemf0 = append(f1elemf0, f1elemf0elem)
				}
				f1elem.Permissions = f1elemf0
			}
			if f1iter.Principal != nil {
				f1elemf1 := &svcapitypes.DataLakePrincipal{}
				if f1iter.Principal.DataLakePrincipalIdentifier != nil {
					f1elemf1.DataLakePrincipalIdentifier = f1iter.Principal.DataLakePrincipalIdentifier
				}
				f1elem.Principal = f1elemf1
			}
			f1 = append(f1, f1elem)
		}
		ko.Spec.TableDefaultPermissions = f1
	} else {
		ko.Spec.TableDefaultPermissions = nil
	}
	if resp.Database.Description != nil {
		ko.Spec.Description = resp.Database.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.Database.FederatedDatabase != nil {
		f4 := &svcapitypes.FederatedDatabase{}
		if resp.Database.FederatedDatabase.ConnectionName != nil {
			f4.ConnectionName = resp.Database.FederatedDatabase.ConnectionName
		}
		if resp.Database.FederatedDatabase.Identifier != nil {
			f4.Identifier = resp.Database.FederatedDatabase.Identifier
		}
		ko.Spec.FederatedDatabase = f4
	} else {
		ko.Spec.FederatedDatabase = nil
	}
	if resp.Database.LocationUri != nil {
		ko.Spec.LocationURI = resp.Database.LocationUri
	} else {
		ko.Spec.LocationURI = nil
	}
	if resp.Database.Name != nil {
		ko.Spec.Name = resp.Database.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Database.Parameters != nil {
		ko.Spec.Parameters = aws.StringMap(resp.Database.Parameters)
	} else {
		ko.Spec.Parameters = nil
	}
	if resp.Database.TargetDatabase != nil {
		f8 := &svcapitypes.DatabaseIdentifier{}
		if resp.Database.TargetDatabase.CatalogId != nil {
			f8.CatalogID = resp.Database.TargetDatabase.CatalogId
		}
		if resp.Database.TargetDatabase.DatabaseName != nil {
			f8.DatabaseName = resp.Database.TargetDatabase.DatabaseName
		}
		if resp.Database.TargetDatabase.Region != nil {
			f8.Region = resp.Database.TargetDatabase.Region
		}
		ko.Spec.TargetDatabase = f8
	} else {
		ko.Spec.TargetDatabase = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	arn := ackv1alpha1.AWSResourceName(databaseARN(ko))
	ko.Status.ACKResourceMetadata.ARN = &arn
	ko.Spec.Tags, err = rm.getTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN))
	if err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetDatabaseInput, error) {
	res := &svcsdk.GetDatabaseInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	input.CatalogId = desired.ko.Spec.CatalogID

	var resp *svcsdk.CreateDatabaseOutput
	_ = resp
	resp, err = rm.sdkapi.CreateDatabase(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateDatabase", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	arn := ackv1alpha1.AWSResourceName(databaseARN(ko))
	ko.Status.ACKResourceMetadata.ARN = &arn

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateDatabaseInput, error) {
	res := &svcsdk.CreateDatabaseInput{}

	fw := &svcsdktypes.DatabaseInput{}
	if r.ko.Spec.TableDefaultPermissions != nil {
		f0 := []svcsdktypes.PrincipalPermissions{}
		for _, f0iter := range r.ko.Spec.TableDefaultPermissions {
			f0elem := &svcsdktypes.PrincipalPermissions{}
			if f0iter.Permissions != nil {
				f0elemf0 := []svcsdktypes.Permission{}
				for _, f0elemf0iter := range f0iter.Permissions {
					var f0elemf0elem string
					f0elemf0elem = string(*f0elemf0iter)
					f0elemf0 = append(f0elemf0, svcsdktypes.Permission(f0elemf0elem))
				}
				f0elem.Permissions = f0elemf0
			}
			if f0iter.Principal != nil {
				f0elemf1 := &svcsdktypes.DataLakePrincipal{}
				if f0iter.Principal.DataLakePrincipalIdentifier != nil {
					f0elemf1.DataLakePrincipalIdentifier = f0iter.Principal.DataLakePrincipalIdentifier
				}
				f0elem.Principal = f0elemf1
			}
			f0 = append(f0, *f0elem)
		}
		fw.CreateTableDefaultPermissions = f0
	}
	if r.ko.Spec.Description != nil {
		fw.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.FederatedDatabase != nil {
		f2 := &svcsdktypes.FederatedDatabase{}
		if r.ko.Spec.FederatedDatabase.ConnectionName != nil {
			f2.ConnectionName = r.ko.Spec.FederatedDatabase.ConnectionName
		}
		if r.ko.Spec.FederatedDatabase.Identifier != nil {
			f2.Identifier = r.ko.Spec.FederatedDatabase.Identifier
		}
		fw.FederatedDatabase = f2
	}
	if r.ko.Spec.LocationURI != nil {
		fw.LocationUri = r.ko.Spec.LocationURI
	}
	if r.ko.Spec.Name != nil {
		fw.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Parameters != nil {
		fw.Parameters = aws.ToStringMap(r.ko.Spec.Parameters)
	}
	if r.ko.Spec.TargetDatabase != nil {
		f6 := &svcsdktypes.DatabaseIdentifier{}
		if r.ko.Spec.TargetDatabase.CatalogID != nil {
			f6.CatalogId = r.ko.Spec.TargetDatabase.CatalogID
		}
		if r.ko.Spec.TargetDatabase.DatabaseName != nil {
			f6.DatabaseName = r.ko.Spec.TargetDatabase.DatabaseName
		}
		if r.ko.Spec.TargetDatabase.Region != nil {
			f6.Region = r.ko.Spec.TargetDatabase.Region
		}
		fw.TargetDatabase = f6
	}
	res.DatabaseInput = fw

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		err := rm.syncTags(
			ctx,
			desired,
			latest,
		)
		if err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	input.CatalogId = desired.ko.Spec.CatalogID
	input.Name = desired.ko.Spec.Name

	var resp *svcsdk.UpdateDatabaseOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateDatabase(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateDatabase", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateDatabaseInput, error) {
	res := &svcsdk.UpdateDatabaseInput{}

	fw := &svcsdktypes.DatabaseInput{}
	if r.ko.Spec.TableDefaultPermissions != nil {
		f0 := []svcsdktypes.PrincipalPermissions{}
		for _, f0iter := range r.ko.Spec.TableDefaultPermissions {
			f0elem := &svcsdktypes.PrincipalPermissions{}
			if f0iter.Permissions != nil {
				f0elemf0 := []svcsdktypes.Permission{}
				for _, f0elemf0iter := range f0iter.Permissions {
					var f0elemf0elem string
					f0elemf0elem = string(*f0elemf0iter)
					f0elemf0 = append(f0elemf0, svcsdktypes.Permission(f0elemf0elem))
				}
				f0elem.Permissions = f0elemf0
			}
			if f0iter.Principal != nil {
				f0elemf1 := &svcsdktypes.DataLakePrincipal{}
				if f0iter.Principal.DataLakePrincipalIdentifier != nil {
					f0elemf1.DataLakePrincipalIdentifier = f0iter.Principal.DataLakePrincipalIdentifier
				}
				f0elem.Principal = f0elemf1
			}
			f0 = append(f0, *f0elem)
		}
		fw.CreateTableDefaultPermissions = f0
	}
	if r.ko.Spec.Description != nil {
		fw.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.FederatedDatabase != nil {
		f2 := &svcsdktypes.FederatedDatabase{}
		if r.ko.Spec.FederatedDatabase.ConnectionName != nil {
			f2.ConnectionName = r.ko.Spec.FederatedDatabase.ConnectionName
		}
		if r.ko.Spec.FederatedDatabase.Identifier != nil {
			f2.Identifier = r.ko.Spec.FederatedDatabase.Identifier
		}
		fw.FederatedDatabase = f2
	}
	if r.ko.Spec.LocationURI != nil {
		fw.LocationUri = r.ko.Spec.LocationURI
	}
	if r.ko.Spec.Name != nil {
		fw.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Parameters != nil {
		fw.Parameters = aws.ToStringMap(r.ko.Spec.Parameters)
	}
	if r.ko.Spec.TargetDatabase != nil {
		f6 := &svcsdktypes.DatabaseIdentifier{}
		if r.ko.Spec.TargetDatabase.CatalogID != nil {
			f6.CatalogId = r.ko.Spec.TargetDatabase.CatalogID
		}
		if r.ko.Spec.TargetDatabase.DatabaseName != nil {
			f6.DatabaseName = r.ko.Spec.TargetDatabase.DatabaseName
		}
		if r.ko.Spec.TargetDatabase.Region != nil {
			f6.Region = r.ko.Spec.TargetDatabase.Region
		}
		fw.TargetDatabase = f6
	}
	res.DatabaseInput = fw

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteDatabaseOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteDatabase(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteDatabase", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteDatabaseInput, error) {
	res := &svcsdk.DeleteDatabaseInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Database,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidInputException":
		return true
	default:
		return false
	}
}
