// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package registry

import (
	"context"
	"errors"
	"fmt"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/glue"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/glue/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/glue-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Registry{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = fmt.Sprintf("")
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()

	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetRegistryOutput
	resp, err = rm.sdkapi.GetRegistry(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetRegistry", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "EntityNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.RegistryName != nil {
		ko.Spec.RegistryName = resp.RegistryName
	} else {
		ko.Spec.RegistryName = nil
	}
	if resp.RegistryArn != nil {
		if ko.Status.ACKResourceMetadata == nil {
			ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
		}
		tmpARN := ackv1alpha1.AWSResourceName(*resp.RegistryArn)
		ko.Status.ACKResourceMetadata.ARN = &tmpARN
		ko.Status.RegistryARN = resp.RegistryArn
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}

	rm.setStatusDefaults(ko)

	// Count dependent schemas for status
	schemaCount, err := rm.countDependentSchemas(ctx, &resource{ko})
	if err != nil {
		rlog.Info("unable to count dependent schemas", "error", err)
		// Don't fail the operation if schema counting fails
	} else {
		ko.Status.DependentSchemaCount = &schemaCount
	}

	latest = &resource{ko}
	return latest, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.RegistryName == nil
}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetRegistryInput, error) {
	res := &svcsdk.GetRegistryInput{}

	if r.ko.Spec.RegistryName != nil {
		res.RegistryId = &svcsdktypes.RegistryId{
			RegistryName: r.ko.Spec.RegistryName,
		}
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()

	// Run pre-create hooks
	if err := rm.preCreate(ctx, desired); err != nil {
		return nil, err
	}

	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateRegistryOutput
	_ = resp
	resp, err = rm.sdkapi.CreateRegistry(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateRegistry", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.RegistryName != nil {
		ko.Spec.RegistryName = resp.RegistryName
	} else {
		ko.Spec.RegistryName = nil
	}
	if resp.RegistryArn != nil {
		if ko.Status.ACKResourceMetadata == nil {
			ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
		}
		tmpARN := ackv1alpha1.AWSResourceName(*resp.RegistryArn)
		ko.Status.ACKResourceMetadata.ARN = &tmpARN
		ko.Status.RegistryARN = resp.RegistryArn
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}

	rm.setStatusDefaults(ko)

	// Initialize dependent schema count (should be 0 for new registry)
	initialCount := int64(0)
	ko.Status.DependentSchemaCount = &initialCount

	created = &resource{ko}

	// Run post-create hooks
	if err := rm.postCreate(ctx, created); err != nil {
		return nil, err
	}

	return created, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateRegistryInput, error) {
	res := &svcsdk.CreateRegistryInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.RegistryName != nil {
		res.RegistryName = r.ko.Spec.RegistryName
	}
	if r.ko.Spec.Tags != nil {
		f2 := map[string]string{}
		for f2key, f2valptr := range r.ko.Spec.Tags {
			var f2val string
			if f2valptr != nil {
				f2val = *f2valptr
			}
			f2[f2key] = f2val
		}
		res.Tags = f2
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()

	// Run pre-update hooks
	if err := rm.preUpdate(ctx, desired, latest); err != nil {
		return nil, err
	}

	// Handle tags separately using syncTags
	if delta.DifferentAt("Spec.Tags") {
		err := rm.syncTags(ctx, desired, latest)
		if err != nil {
			return nil, err
		}
	}

	// If only tags changed, return desired resource
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateRegistryOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateRegistry(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateRegistry", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.RegistryName != nil {
		ko.Spec.RegistryName = resp.RegistryName
	} else {
		ko.Spec.RegistryName = nil
	}
	if resp.RegistryArn != nil {
		if ko.Status.ACKResourceMetadata == nil {
			ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
		}
		tmpARN := ackv1alpha1.AWSResourceName(*resp.RegistryArn)
		ko.Status.ACKResourceMetadata.ARN = &tmpARN
		ko.Status.RegistryARN = resp.RegistryArn
	}

	rm.setStatusDefaults(ko)

	// Count dependent schemas for status
	schemaCount, err := rm.countDependentSchemas(ctx, &resource{ko})
	if err != nil {
		rlog.Info("unable to count dependent schemas", "error", err)
		// Don't fail the operation if schema counting fails
	} else {
		ko.Status.DependentSchemaCount = &schemaCount
	}

	updated = &resource{ko}

	// Run post-update hooks
	if err := rm.postUpdate(ctx, desired, updated); err != nil {
		return nil, err
	}

	return updated, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateRegistryInput, error) {
	res := &svcsdk.UpdateRegistryInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.RegistryName != nil {
		res.RegistryId = &svcsdktypes.RegistryId{
			RegistryName: r.ko.Spec.RegistryName,
		}
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()

	// Run pre-delete hooks (includes deletion policy check)
	if err := rm.preDelete(ctx, r); err != nil {
		return nil, err
	}

	// Check if we should actually delete from AWS
	if !rm.shouldDeleteFromAWS(r) {
		rlog.Info("deletion policy is Retain, skipping AWS deletion")
		// Run post-delete hooks even for Retain policy
		if err := rm.postDelete(ctx, r); err != nil {
			return nil, err
		}
		return nil, nil
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteRegistryOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteRegistry(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteRegistry", err)
	if err != nil {
		return nil, err
	}

	// Run post-delete hooks
	if err := rm.postDelete(ctx, r); err != nil {
		return nil, err
	}

	return nil, nil
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteRegistryInput, error) {
	res := &svcsdk.DeleteRegistryInput{}

	if r.ko.Spec.RegistryName != nil {
		res.RegistryId = &svcsdktypes.RegistryId{
			RegistryName: r.ko.Spec.RegistryName,
		}
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Registry,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions updates the resource's conditions based on the operation result
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidInputException",
		"AccessDeniedException":
		return true
	default:
		return false
	}
}
