// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package table

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CatalogID, b.ko.Spec.CatalogID) {
		delta.Add("Spec.CatalogID", a.ko.Spec.CatalogID, b.ko.Spec.CatalogID)
	} else if a.ko.Spec.CatalogID != nil && b.ko.Spec.CatalogID != nil {
		if *a.ko.Spec.CatalogID != *b.ko.Spec.CatalogID {
			delta.Add("Spec.CatalogID", a.ko.Spec.CatalogID, b.ko.Spec.CatalogID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DatabaseName, b.ko.Spec.DatabaseName) {
		delta.Add("Spec.DatabaseName", a.ko.Spec.DatabaseName, b.ko.Spec.DatabaseName)
	} else if a.ko.Spec.DatabaseName != nil && b.ko.Spec.DatabaseName != nil {
		if *a.ko.Spec.DatabaseName != *b.ko.Spec.DatabaseName {
			delta.Add("Spec.DatabaseName", a.ko.Spec.DatabaseName, b.ko.Spec.DatabaseName)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.DatabaseRef, b.ko.Spec.DatabaseRef) {
		delta.Add("Spec.DatabaseRef", a.ko.Spec.DatabaseRef, b.ko.Spec.DatabaseRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Owner, b.ko.Spec.Owner) {
		delta.Add("Spec.Owner", a.ko.Spec.Owner, b.ko.Spec.Owner)
	} else if a.ko.Spec.Owner != nil && b.ko.Spec.Owner != nil {
		if *a.ko.Spec.Owner != *b.ko.Spec.Owner {
			delta.Add("Spec.Owner", a.ko.Spec.Owner, b.ko.Spec.Owner)
		}
	}
	if len(a.ko.Spec.Parameters) != len(b.ko.Spec.Parameters) {
		delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
	} else if len(a.ko.Spec.Parameters) > 0 {
		if !ackcompare.MapStringStringPEqual(a.ko.Spec.Parameters, b.ko.Spec.Parameters) {
			delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
		}
	}
	if len(a.ko.Spec.PartitionKeys) != len(b.ko.Spec.PartitionKeys) {
		delta.Add("Spec.PartitionKeys", a.ko.Spec.PartitionKeys, b.ko.Spec.PartitionKeys)
	} else if len(a.ko.Spec.PartitionKeys) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.PartitionKeys, b.ko.Spec.PartitionKeys) {
			delta.Add("Spec.PartitionKeys", a.ko.Spec.PartitionKeys, b.ko.Spec.PartitionKeys)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Retention, b.ko.Spec.Retention) {
		if !ackcompare.IsNilEqualsZero(a.ko.Spec.Retention, b.ko.Spec.Retention) {
			delta.Add("Spec.Retention", a.ko.Spec.Retention, b.ko.Spec.Retention)
		}
	} else if a.ko.Spec.Retention != nil && b.ko.Spec.Retention != nil {
		if *a.ko.Spec.Retention != *b.ko.Spec.Retention {
			delta.Add("Spec.Retention", a.ko.Spec.Retention, b.ko.Spec.Retention)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor, b.ko.Spec.StorageDescriptor) {
		delta.Add("Spec.StorageDescriptor", a.ko.Spec.StorageDescriptor, b.ko.Spec.StorageDescriptor)
	} else if a.ko.Spec.StorageDescriptor != nil && b.ko.Spec.StorageDescriptor != nil {
		if len(a.ko.Spec.StorageDescriptor.AdditionalLocations) != len(b.ko.Spec.StorageDescriptor.AdditionalLocations) {
			delta.Add("Spec.StorageDescriptor.AdditionalLocations", a.ko.Spec.StorageDescriptor.AdditionalLocations, b.ko.Spec.StorageDescriptor.AdditionalLocations)
		} else if len(a.ko.Spec.StorageDescriptor.AdditionalLocations) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.StorageDescriptor.AdditionalLocations, b.ko.Spec.StorageDescriptor.AdditionalLocations) {
				delta.Add("Spec.StorageDescriptor.AdditionalLocations", a.ko.Spec.StorageDescriptor.AdditionalLocations, b.ko.Spec.StorageDescriptor.AdditionalLocations)
			}
		}
		if len(a.ko.Spec.StorageDescriptor.BucketColumns) != len(b.ko.Spec.StorageDescriptor.BucketColumns) {
			delta.Add("Spec.StorageDescriptor.BucketColumns", a.ko.Spec.StorageDescriptor.BucketColumns, b.ko.Spec.StorageDescriptor.BucketColumns)
		} else if len(a.ko.Spec.StorageDescriptor.BucketColumns) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.StorageDescriptor.BucketColumns, b.ko.Spec.StorageDescriptor.BucketColumns) {
				delta.Add("Spec.StorageDescriptor.BucketColumns", a.ko.Spec.StorageDescriptor.BucketColumns, b.ko.Spec.StorageDescriptor.BucketColumns)
			}
		}
		if len(a.ko.Spec.StorageDescriptor.Columns) != len(b.ko.Spec.StorageDescriptor.Columns) {
			delta.Add("Spec.StorageDescriptor.Columns", a.ko.Spec.StorageDescriptor.Columns, b.ko.Spec.StorageDescriptor.Columns)
		} else if len(a.ko.Spec.StorageDescriptor.Columns) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.StorageDescriptor.Columns, b.ko.Spec.StorageDescriptor.Columns) {
				delta.Add("Spec.StorageDescriptor.Columns", a.ko.Spec.StorageDescriptor.Columns, b.ko.Spec.StorageDescriptor.Columns)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.Compressed, b.ko.Spec.StorageDescriptor.Compressed) {
			if !ackcompare.IsNilEqualsZero(a.ko.Spec.StorageDescriptor.Compressed, b.ko.Spec.StorageDescriptor.Compressed) {
				delta.Add("Spec.StorageDescriptor.Compressed", a.ko.Spec.StorageDescriptor.Compressed, b.ko.Spec.StorageDescriptor.Compressed)
			}
		} else if a.ko.Spec.StorageDescriptor.Compressed != nil && b.ko.Spec.StorageDescriptor.Compressed != nil {
			if *a.ko.Spec.StorageDescriptor.Compressed != *b.ko.Spec.StorageDescriptor.Compressed {
				delta.Add("Spec.StorageDescriptor.Compressed", a.ko.Spec.StorageDescriptor.Compressed, b.ko.Spec.StorageDescriptor.Compressed)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.InputFormat, b.ko.Spec.StorageDescriptor.InputFormat) {
			delta.Add("Spec.StorageDescriptor.InputFormat", a.ko.Spec.StorageDescriptor.InputFormat, b.ko.Spec.StorageDescriptor.InputFormat)
		} else if a.ko.Spec.StorageDescriptor.InputFormat != nil && b.ko.Spec.StorageDescriptor.InputFormat != nil {
			if *a.ko.Spec.StorageDescriptor.InputFormat != *b.ko.Spec.StorageDescriptor.InputFormat {
				delta.Add("Spec.StorageDescriptor.InputFormat", a.ko.Spec.StorageDescriptor.InputFormat, b.ko.Spec.StorageDescriptor.InputFormat)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.Location, b.ko.Spec.StorageDescriptor.Location) {
			delta.Add("Spec.StorageDescriptor.Location", a.ko.Spec.StorageDescriptor.Location, b.ko.Spec.StorageDescriptor.Location)
		} else if a.ko.Spec.StorageDescriptor.Location != nil && b.ko.Spec.StorageDescriptor.Location != nil {
			if *a.ko.Spec.StorageDescriptor.Location != *b.ko.Spec.StorageDescriptor.Location {
				delta.Add("Spec.StorageDescriptor.Location", a.ko.Spec.StorageDescriptor.Location, b.ko.Spec.StorageDescriptor.Location)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.NumberOfBuckets, b.ko.Spec.StorageDescriptor.NumberOfBuckets) {
			if !ackcompare.IsNilEqualsZero(a.ko.Spec.StorageDescriptor.NumberOfBuckets, b.ko.Spec.StorageDescriptor.NumberOfBuckets) {
				delta.Add("Spec.StorageDescriptor.NumberOfBuckets", a.ko.Spec.StorageDescriptor.NumberOfBuckets, b.ko.Spec.StorageDescriptor.NumberOfBuckets)
			}
		} else if a.ko.Spec.StorageDescriptor.NumberOfBuckets != nil && b.ko.Spec.StorageDescriptor.NumberOfBuckets != nil {
			if *a.ko.Spec.StorageDescriptor.NumberOfBuckets != *b.ko.Spec.StorageDescriptor.NumberOfBuckets {
				delta.Add("Spec.StorageDescriptor.NumberOfBuckets", a.ko.Spec.StorageDescriptor.NumberOfBuckets, b.ko.Spec.StorageDescriptor.NumberOfBuckets)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.OutputFormat, b.ko.Spec.StorageDescriptor.OutputFormat) {
			delta.Add("Spec.StorageDescriptor.OutputFormat", a.ko.Spec.StorageDescriptor.OutputFormat, b.ko.Spec.StorageDescriptor.OutputFormat)
		} else if a.ko.Spec.StorageDescriptor.OutputFormat != nil && b.ko.Spec.StorageDescriptor.OutputFormat != nil {
			if *a.ko.Spec.StorageDescriptor.OutputFormat != *b.ko.Spec.StorageDescriptor.OutputFormat {
				delta.Add("Spec.StorageDescriptor.OutputFormat", a.ko.Spec.StorageDescriptor.OutputFormat, b.ko.Spec.StorageDescriptor.OutputFormat)
			}
		}
		if len(a.ko.Spec.StorageDescriptor.Parameters) != len(b.ko.Spec.StorageDescriptor.Parameters) {
			delta.Add("Spec.StorageDescriptor.Parameters", a.ko.Spec.StorageDescriptor.Parameters, b.ko.Spec.StorageDescriptor.Parameters)
		} else if len(a.ko.Spec.StorageDescriptor.Parameters) > 0 {
			if !ackcompare.MapStringStringPEqual(a.ko.Spec.StorageDescriptor.Parameters, b.ko.Spec.StorageDescriptor.Parameters) {
				delta.Add("Spec.StorageDescriptor.Parameters", a.ko.Spec.StorageDescriptor.Parameters, b.ko.Spec.StorageDescriptor.Parameters)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SchemaReference, b.ko.Spec.StorageDescriptor.SchemaReference) {
			delta.Add("Spec.StorageDescriptor.SchemaReference", a.ko.Spec.StorageDescriptor.SchemaReference, b.ko.Spec.StorageDescriptor.SchemaReference)
		} else if a.ko.Spec.StorageDescriptor.SchemaReference != nil && b.ko.Spec.StorageDescriptor.SchemaReference != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID) {
				delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaID", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID)
			} else if a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID != nil && b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName) {
					delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName)
				} else if a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName != nil && b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName != nil {
					if *a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName != *b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName {
						delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN) {
					delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN)
				} else if a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN != nil && b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN != nil {
					if *a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN != *b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN {
						delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName) {
					delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName)
				} else if a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName != nil && b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName != nil {
					if *a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName != *b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName {
						delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID) {
				delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaVersionID", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID)
			} else if a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID != nil && b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID != nil {
				if *a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID != *b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID {
					delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaVersionID", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber) {
				delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber)
			} else if a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber != nil && b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber != nil {
				if *a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber != *b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber {
					delta.Add("Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber", a.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber, b.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SerdeInfo, b.ko.Spec.StorageDescriptor.SerdeInfo) {
			delta.Add("Spec.StorageDescriptor.SerdeInfo", a.ko.Spec.StorageDescriptor.SerdeInfo, b.ko.Spec.StorageDescriptor.SerdeInfo)
		} else if a.ko.Spec.StorageDescriptor.SerdeInfo != nil && b.ko.Spec.StorageDescriptor.SerdeInfo != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SerdeInfo.Name, b.ko.Spec.StorageDescriptor.SerdeInfo.Name) {
				delta.Add("Spec.StorageDescriptor.SerdeInfo.Name", a.ko.Spec.StorageDescriptor.SerdeInfo.Name, b.ko.Spec.StorageDescriptor.SerdeInfo.Name)
			} else if a.ko.Spec.StorageDescriptor.SerdeInfo.Name != nil && b.ko.Spec.StorageDescriptor.SerdeInfo.Name != nil {
				if *a.ko.Spec.StorageDescriptor.SerdeInfo.Name != *b.ko.Spec.StorageDescriptor.SerdeInfo.Name {
					delta.Add("Spec.StorageDescriptor.SerdeInfo.Name", a.ko.Spec.StorageDescriptor.SerdeInfo.Name, b.ko.Spec.StorageDescriptor.SerdeInfo.Name)
				}
			}
			if len(a.ko.Spec.StorageDescriptor.SerdeInfo.Parameters) != len(b.ko.Spec.StorageDescriptor.SerdeInfo.Parameters) {
				delta.Add("Spec.StorageDescriptor.SerdeInfo.Parameters", a.ko.Spec.StorageDescriptor.SerdeInfo.Parameters, b.ko.Spec.StorageDescriptor.SerdeInfo.Parameters)
			} else if len(a.ko.Spec.StorageDescriptor.SerdeInfo.Parameters) > 0 {
				if !ackcompare.MapStringStringPEqual(a.ko.Spec.StorageDescriptor.SerdeInfo.Parameters, b.ko.Spec.StorageDescriptor.SerdeInfo.Parameters) {
					delta.Add("Spec.StorageDescriptor.SerdeInfo.Parameters", a.ko.Spec.StorageDescriptor.SerdeInfo.Parameters, b.ko.Spec.StorageDescriptor.SerdeInfo.Parameters)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary, b.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary) {
				delta.Add("Spec.StorageDescriptor.SerdeInfo.SerializationLibrary", a.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary, b.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary)
			} else if a.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary != nil && b.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary != nil {
				if *a.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary != *b.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary {
					delta.Add("Spec.StorageDescriptor.SerdeInfo.SerializationLibrary", a.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary, b.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.SkewedInfo, b.ko.Spec.StorageDescriptor.SkewedInfo) {
			delta.Add("Spec.StorageDescriptor.SkewedInfo", a.ko.Spec.StorageDescriptor.SkewedInfo, b.ko.Spec.StorageDescriptor.SkewedInfo)
		} else if a.ko.Spec.StorageDescriptor.SkewedInfo != nil && b.ko.Spec.StorageDescriptor.SkewedInfo != nil {
			if len(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames) != len(b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames) {
				delta.Add("Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames", a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames)
			} else if len(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames) {
					delta.Add("Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames", a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames)
				}
			}
			if len(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps) != len(b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps) {
				delta.Add("Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps", a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps)
			} else if len(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps) > 0 {
				if !ackcompare.MapStringStringPEqual(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps) {
					delta.Add("Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps", a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps)
				}
			}
			if len(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues) != len(b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues) {
				delta.Add("Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues", a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues)
			} else if len(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues) {
					delta.Add("Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues", a.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues, b.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues)
				}
			}
		}
		if len(a.ko.Spec.StorageDescriptor.SortColumns) != len(b.ko.Spec.StorageDescriptor.SortColumns) {
			delta.Add("Spec.StorageDescriptor.SortColumns", a.ko.Spec.StorageDescriptor.SortColumns, b.ko.Spec.StorageDescriptor.SortColumns)
		} else if len(a.ko.Spec.StorageDescriptor.SortColumns) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.StorageDescriptor.SortColumns, b.ko.Spec.StorageDescriptor.SortColumns) {
				delta.Add("Spec.StorageDescriptor.SortColumns", a.ko.Spec.StorageDescriptor.SortColumns, b.ko.Spec.StorageDescriptor.SortColumns)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor.StoredAsSubDirectories, b.ko.Spec.StorageDescriptor.StoredAsSubDirectories) {
			if !ackcompare.IsNilEqualsZero(a.ko.Spec.StorageDescriptor.StoredAsSubDirectories, b.ko.Spec.StorageDescriptor.StoredAsSubDirectories) {
				delta.Add("Spec.StorageDescriptor.StoredAsSubDirectories", a.ko.Spec.StorageDescriptor.StoredAsSubDirectories, b.ko.Spec.StorageDescriptor.StoredAsSubDirectories)
			}
		} else if a.ko.Spec.StorageDescriptor.StoredAsSubDirectories != nil && b.ko.Spec.StorageDescriptor.StoredAsSubDirectories != nil {
			if *a.ko.Spec.StorageDescriptor.StoredAsSubDirectories != *b.ko.Spec.StorageDescriptor.StoredAsSubDirectories {
				delta.Add("Spec.StorageDescriptor.StoredAsSubDirectories", a.ko.Spec.StorageDescriptor.StoredAsSubDirectories, b.ko.Spec.StorageDescriptor.StoredAsSubDirectories)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TableType, b.ko.Spec.TableType) {
		delta.Add("Spec.TableType", a.ko.Spec.TableType, b.ko.Spec.TableType)
	} else if a.ko.Spec.TableType != nil && b.ko.Spec.TableType != nil {
		if *a.ko.Spec.TableType != *b.ko.Spec.TableType {
			delta.Add("Spec.TableType", a.ko.Spec.TableType, b.ko.Spec.TableType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TargetTable, b.ko.Spec.TargetTable) {
		delta.Add("Spec.TargetTable", a.ko.Spec.TargetTable, b.ko.Spec.TargetTable)
	} else if a.ko.Spec.TargetTable != nil && b.ko.Spec.TargetTable != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.TargetTable.CatalogID, b.ko.Spec.TargetTable.CatalogID) {
			delta.Add("Spec.TargetTable.CatalogID", a.ko.Spec.TargetTable.CatalogID, b.ko.Spec.TargetTable.CatalogID)
		} else if a.ko.Spec.TargetTable.CatalogID != nil && b.ko.Spec.TargetTable.CatalogID != nil {
			if *a.ko.Spec.TargetTable.CatalogID != *b.ko.Spec.TargetTable.CatalogID {
				delta.Add("Spec.TargetTable.CatalogID", a.ko.Spec.TargetTable.CatalogID, b.ko.Spec.TargetTable.CatalogID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.TargetTable.DatabaseName, b.ko.Spec.TargetTable.DatabaseName) {
			delta.Add("Spec.TargetTable.DatabaseName", a.ko.Spec.TargetTable.DatabaseName, b.ko.Spec.TargetTable.DatabaseName)
		} else if a.ko.Spec.TargetTable.DatabaseName != nil && b.ko.Spec.TargetTable.DatabaseName != nil {
			if *a.ko.Spec.TargetTable.DatabaseName != *b.ko.Spec.TargetTable.DatabaseName {
				delta.Add("Spec.TargetTable.DatabaseName", a.ko.Spec.TargetTable.DatabaseName, b.ko.Spec.TargetTable.DatabaseName)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.TargetTable.Name, b.ko.Spec.TargetTable.Name) {
			delta.Add("Spec.TargetTable.Name", a.ko.Spec.TargetTable.Name, b.ko.Spec.TargetTable.Name)
		} else if a.ko.Spec.TargetTable.Name != nil && b.ko.Spec.TargetTable.Name != nil {
			if *a.ko.Spec.TargetTable.Name != *b.ko.Spec.TargetTable.Name {
				delta.Add("Spec.TargetTable.Name", a.ko.Spec.TargetTable.Name, b.ko.Spec.TargetTable.Name)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.TargetTable.Region, b.ko.Spec.TargetTable.Region) {
			delta.Add("Spec.TargetTable.Region", a.ko.Spec.TargetTable.Region, b.ko.Spec.TargetTable.Region)
		} else if a.ko.Spec.TargetTable.Region != nil && b.ko.Spec.TargetTable.Region != nil {
			if *a.ko.Spec.TargetTable.Region != *b.ko.Spec.TargetTable.Region {
				delta.Add("Spec.TargetTable.Region", a.ko.Spec.TargetTable.Region, b.ko.Spec.TargetTable.Region)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ViewExpandedText, b.ko.Spec.ViewExpandedText) {
		delta.Add("Spec.ViewExpandedText", a.ko.Spec.ViewExpandedText, b.ko.Spec.ViewExpandedText)
	} else if a.ko.Spec.ViewExpandedText != nil && b.ko.Spec.ViewExpandedText != nil {
		if *a.ko.Spec.ViewExpandedText != *b.ko.Spec.ViewExpandedText {
			delta.Add("Spec.ViewExpandedText", a.ko.Spec.ViewExpandedText, b.ko.Spec.ViewExpandedText)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ViewOriginalText, b.ko.Spec.ViewOriginalText) {
		delta.Add("Spec.ViewOriginalText", a.ko.Spec.ViewOriginalText, b.ko.Spec.ViewOriginalText)
	} else if a.ko.Spec.ViewOriginalText != nil && b.ko.Spec.ViewOriginalText != nil {
		if *a.ko.Spec.ViewOriginalText != *b.ko.Spec.ViewOriginalText {
			delta.Add("Spec.ViewOriginalText", a.ko.Spec.ViewOriginalText, b.ko.Spec.ViewOriginalText)
		}
	}

	return delta
}
