// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package table

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/glue"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/glue/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/glue-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Table{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetTableOutput
	resp, err = rm.sdkapi.GetTable(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetTable", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "EntityNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Table.CatalogId != nil {
		ko.Spec.CatalogID = resp.Table.CatalogId
	} else {
		ko.Spec.CatalogID = nil
	}
	if resp.Table.DatabaseName != nil {
		ko.Spec.DatabaseName = resp.Table.DatabaseName
	} else {
		ko.Spec.DatabaseName = nil
	}
	if resp.Table.Description != nil {
		ko.Spec.Description = resp.Table.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.Table.Name != nil {
		ko.Spec.Name = resp.Table.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Table.Owner != nil {
		ko.Spec.Owner = resp.Table.Owner
	} else {
		ko.Spec.Owner = nil
	}
	if resp.Table.Parameters != nil {
		ko.Spec.Parameters = aws.StringMap(resp.Table.Parameters)
	} else {
		ko.Spec.Parameters = nil
	}
	if resp.Table.PartitionKeys != nil {
		f13 := []*svcapitypes.Column{}
		for _, f13iter := range resp.Table.PartitionKeys {
			f13elem := &svcapitypes.Column{}
			if f13iter.Comment != nil {
				f13elem.Comment = f13iter.Comment
			}
			if f13iter.Name != nil {
				f13elem.Name = f13iter.Name
			}
			if f13iter.Parameters != nil {
				f13elem.Parameters = aws.StringMap(f13iter.Parameters)
			}
			if f13iter.Type != nil {
				f13elem.Type = f13iter.Type
			}
			f13 = append(f13, f13elem)
		}
		ko.Spec.PartitionKeys = f13
	} else {
		ko.Spec.PartitionKeys = nil
	}
	retentionCopy := int64(resp.Table.Retention)
	ko.Spec.Retention = &retentionCopy
	if resp.Table.StorageDescriptor != nil {
		f15 := &svcapitypes.StorageDescriptor{}
		if resp.Table.StorageDescriptor.AdditionalLocations != nil {
			f15.AdditionalLocations = aws.StringSlice(resp.Table.StorageDescriptor.AdditionalLocations)
		}
		if resp.Table.StorageDescriptor.BucketColumns != nil {
			f15.BucketColumns = aws.StringSlice(resp.Table.StorageDescriptor.BucketColumns)
		}
		if resp.Table.StorageDescriptor.Columns != nil {
			f15f2 := []*svcapitypes.Column{}
			for _, f15f2iter := range resp.Table.StorageDescriptor.Columns {
				f15f2elem := &svcapitypes.Column{}
				if f15f2iter.Comment != nil {
					f15f2elem.Comment = f15f2iter.Comment
				}
				if f15f2iter.Name != nil {
					f15f2elem.Name = f15f2iter.Name
				}
				if f15f2iter.Parameters != nil {
					f15f2elem.Parameters = aws.StringMap(f15f2iter.Parameters)
				}
				if f15f2iter.Type != nil {
					f15f2elem.Type = f15f2iter.Type
				}
				f15f2 = append(f15f2, f15f2elem)
			}
			f15.Columns = f15f2
		}
		f15.Compressed = &resp.Table.StorageDescriptor.Compressed
		if resp.Table.StorageDescriptor.InputFormat != nil {
			f15.InputFormat = resp.Table.StorageDescriptor.InputFormat
		}
		if resp.Table.StorageDescriptor.Location != nil {
			f15.Location = resp.Table.StorageDescriptor.Location
		}
		numberOfBucketsCopy := int64(resp.Table.StorageDescriptor.NumberOfBuckets)
		f15.NumberOfBuckets = &numberOfBucketsCopy
		if resp.Table.StorageDescriptor.OutputFormat != nil {
			f15.OutputFormat = resp.Table.StorageDescriptor.OutputFormat
		}
		if resp.Table.StorageDescriptor.Parameters != nil {
			f15.Parameters = aws.StringMap(resp.Table.StorageDescriptor.Parameters)
		}
		if resp.Table.StorageDescriptor.SchemaReference != nil {
			f15f9 := &svcapitypes.SchemaReference{}
			if resp.Table.StorageDescriptor.SchemaReference.SchemaId != nil {
				f15f9f0 := &svcapitypes.SchemaID{}
				if resp.Table.StorageDescriptor.SchemaReference.SchemaId.RegistryName != nil {
					f15f9f0.RegistryName = resp.Table.StorageDescriptor.SchemaReference.SchemaId.RegistryName
				}
				if resp.Table.StorageDescriptor.SchemaReference.SchemaId.SchemaArn != nil {
					f15f9f0.SchemaARN = resp.Table.StorageDescriptor.SchemaReference.SchemaId.SchemaArn
				}
				if resp.Table.StorageDescriptor.SchemaReference.SchemaId.SchemaName != nil {
					f15f9f0.SchemaName = resp.Table.StorageDescriptor.SchemaReference.SchemaId.SchemaName
				}
				f15f9.SchemaID = f15f9f0
			}
			if resp.Table.StorageDescriptor.SchemaReference.SchemaVersionId != nil {
				f15f9.SchemaVersionID = resp.Table.StorageDescriptor.SchemaReference.SchemaVersionId
			}
			if resp.Table.StorageDescriptor.SchemaReference.SchemaVersionNumber != nil {
				f15f9.SchemaVersionNumber = resp.Table.StorageDescriptor.SchemaReference.SchemaVersionNumber
			}
			f15.SchemaReference = f15f9
		}
		if resp.Table.StorageDescriptor.SerdeInfo != nil {
			f15f10 := &svcapitypes.SerDeInfo{}
			if resp.Table.StorageDescriptor.SerdeInfo.Name != nil {
				f15f10.Name = resp.Table.StorageDescriptor.SerdeInfo.Name
			}
			if resp.Table.StorageDescriptor.SerdeInfo.Parameters != nil {
				f15f10.Parameters = aws.StringMap(resp.Table.StorageDescriptor.SerdeInfo.Parameters)
			}
			if resp.Table.StorageDescriptor.SerdeInfo.SerializationLibrary != nil {
				f15f10.SerializationLibrary = resp.Table.StorageDescriptor.SerdeInfo.SerializationLibrary
			}
			f15.SerdeInfo = f15f10
		}
		if resp.Table.StorageDescriptor.SkewedInfo != nil {
			f15f11 := &svcapitypes.SkewedInfo{}
			if resp.Table.StorageDescriptor.SkewedInfo.SkewedColumnNames != nil {
				f15f11.SkewedColumnNames = aws.StringSlice(resp.Table.StorageDescriptor.SkewedInfo.SkewedColumnNames)
			}
			if resp.Table.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps != nil {
				f15f11.SkewedColumnValueLocationMaps = aws.StringMap(resp.Table.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps)
			}
			if resp.Table.StorageDescriptor.SkewedInfo.SkewedColumnValues != nil {
				f15f11.SkewedColumnValues = aws.StringSlice(resp.Table.StorageDescriptor.SkewedInfo.SkewedColumnValues)
			}
			f15.SkewedInfo = f15f11
		}
		if resp.Table.StorageDescriptor.SortColumns != nil {
			f15f12 := []*svcapitypes.Order{}
			for _, f15f12iter := range resp.Table.StorageDescriptor.SortColumns {
				f15f12elem := &svcapitypes.Order{}
				if f15f12iter.Column != nil {
					f15f12elem.Column = f15f12iter.Column
				}
				sortOrderCopy := int64(f15f12iter.SortOrder)
				f15f12elem.SortOrder = &sortOrderCopy
				f15f12 = append(f15f12, f15f12elem)
			}
			f15.SortColumns = f15f12
		}
		f15.StoredAsSubDirectories = &resp.Table.StorageDescriptor.StoredAsSubDirectories
		ko.Spec.StorageDescriptor = f15
	} else {
		ko.Spec.StorageDescriptor = nil
	}
	if resp.Table.TableType != nil {
		ko.Spec.TableType = resp.Table.TableType
	} else {
		ko.Spec.TableType = nil
	}
	if resp.Table.TargetTable != nil {
		f17 := &svcapitypes.TableIdentifier{}
		if resp.Table.TargetTable.CatalogId != nil {
			f17.CatalogID = resp.Table.TargetTable.CatalogId
		}
		if resp.Table.TargetTable.DatabaseName != nil {
			f17.DatabaseName = resp.Table.TargetTable.DatabaseName
		}
		if resp.Table.TargetTable.Name != nil {
			f17.Name = resp.Table.TargetTable.Name
		}
		if resp.Table.TargetTable.Region != nil {
			f17.Region = resp.Table.TargetTable.Region
		}
		ko.Spec.TargetTable = f17
	} else {
		ko.Spec.TargetTable = nil
	}
	if resp.Table.ViewExpandedText != nil {
		ko.Spec.ViewExpandedText = resp.Table.ViewExpandedText
	} else {
		ko.Spec.ViewExpandedText = nil
	}
	if resp.Table.ViewOriginalText != nil {
		ko.Spec.ViewOriginalText = resp.Table.ViewOriginalText
	} else {
		ko.Spec.ViewOriginalText = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	arn := ackv1alpha1.AWSResourceName(tableARN(ko))
	ko.Status.ACKResourceMetadata.ARN = &arn

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.DatabaseName == nil || r.ko.Spec.Name == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetTableInput, error) {
	res := &svcsdk.GetTableInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.DatabaseName != nil {
		res.DatabaseName = r.ko.Spec.DatabaseName
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	input.CatalogId = desired.ko.Spec.CatalogID
	input.DatabaseName = desired.ko.Spec.DatabaseName

	var resp *svcsdk.CreateTableOutput
	_ = resp
	resp, err = rm.sdkapi.CreateTable(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateTable", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	arn := ackv1alpha1.AWSResourceName(tableARN(ko))
	ko.Status.ACKResourceMetadata.ARN = &arn

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateTableInput, error) {
	res := &svcsdk.CreateTableInput{}

	fw := &svcsdktypes.TableInput{}
	if r.ko.Spec.Description != nil {
		fw.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.Name != nil {
		fw.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Owner != nil {
		fw.Owner = r.ko.Spec.Owner
	}
	if r.ko.Spec.Parameters != nil {
		fw.Parameters = aws.ToStringMap(r.ko.Spec.Parameters)
	}
	if r.ko.Spec.PartitionKeys != nil {
		f4 := []svcsdktypes.Column{}
		for _, f4iter := range r.ko.Spec.PartitionKeys {
			f4elem := &svcsdktypes.Column{}
			if f4iter.Comment != nil {
				f4elem.Comment = f4iter.Comment
			}
			if f4iter.Name != nil {
				f4elem.Name = f4iter.Name
			}
			if f4iter.Parameters != nil {
				f4elem.Parameters = aws.ToStringMap(f4iter.Parameters)
			}
			if f4iter.Type != nil {
				f4elem.Type = f4iter.Type
			}
			f4 = append(f4, *f4elem)
		}
		fw.PartitionKeys = f4
	}
	if r.ko.Spec.Retention != nil {
		retentionCopy0 := *r.ko.Spec.Retention
		if retentionCopy0 > math.MaxInt32 || retentionCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Retention is of type int32")
		}
		retentionCopy := int32(retentionCopy0)
		fw.Retention = retentionCopy
	}
	if r.ko.Spec.StorageDescriptor != nil {
		f6 := &svcsdktypes.StorageDescriptor{}
		if r.ko.Spec.StorageDescriptor.AdditionalLocations != nil {
			f6.AdditionalLocations = aws.ToStringSlice(r.ko.Spec.StorageDescriptor.AdditionalLocations)
		}
		if r.ko.Spec.StorageDescriptor.BucketColumns != nil {
			f6.BucketColumns = aws.ToStringSlice(r.ko.Spec.StorageDescriptor.BucketColumns)
		}
		if r.ko.Spec.StorageDescriptor.Columns != nil {
			f6f2 := []svcsdktypes.Column{}
			for _, f6f2iter := range r.ko.Spec.StorageDescriptor.Columns {
				f6f2elem := &svcsdktypes.Column{}
				if f6f2iter.Comment != nil {
					f6f2elem.Comment = f6f2iter.Comment
				}
				if f6f2iter.Name != nil {
					f6f2elem.Name = f6f2iter.Name
				}
				if f6f2iter.Parameters != nil {
					f6f2elem.Parameters = aws.ToStringMap(f6f2iter.Parameters)
				}
				if f6f2iter.Type != nil {
					f6f2elem.Type = f6f2iter.Type
				}
				f6f2 = append(f6f2, *f6f2elem)
			}
			f6.Columns = f6f2
		}
		if r.ko.Spec.StorageDescriptor.Compressed != nil {
			f6.Compressed = *r.ko.Spec.StorageDescriptor.Compressed
		}
		if r.ko.Spec.StorageDescriptor.InputFormat != nil {
			f6.InputFormat = r.ko.Spec.StorageDescriptor.InputFormat
		}
		if r.ko.Spec.StorageDescriptor.Location != nil {
			f6.Location = r.ko.Spec.StorageDescriptor.Location
		}
		if r.ko.Spec.StorageDescriptor.NumberOfBuckets != nil {
			numberOfBucketsCopy0 := *r.ko.Spec.StorageDescriptor.NumberOfBuckets
			if numberOfBucketsCopy0 > math.MaxInt32 || numberOfBucketsCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field NumberOfBuckets is of type int32")
			}
			numberOfBucketsCopy := int32(numberOfBucketsCopy0)
			f6.NumberOfBuckets = numberOfBucketsCopy
		}
		if r.ko.Spec.StorageDescriptor.OutputFormat != nil {
			f6.OutputFormat = r.ko.Spec.StorageDescriptor.OutputFormat
		}
		if r.ko.Spec.StorageDescriptor.Parameters != nil {
			f6.Parameters = aws.ToStringMap(r.ko.Spec.StorageDescriptor.Parameters)
		}
		if r.ko.Spec.StorageDescriptor.SchemaReference != nil {
			f6f9 := &svcsdktypes.SchemaReference{}
			if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID != nil {
				f6f9f0 := &svcsdktypes.SchemaId{}
				if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName != nil {
					f6f9f0.RegistryName = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName
				}
				if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN != nil {
					f6f9f0.SchemaArn = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN
				}
				if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName != nil {
					f6f9f0.SchemaName = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName
				}
				f6f9.SchemaId = f6f9f0
			}
			if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID != nil {
				f6f9.SchemaVersionId = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID
			}
			if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber != nil {
				f6f9.SchemaVersionNumber = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber
			}
			f6.SchemaReference = f6f9
		}
		if r.ko.Spec.StorageDescriptor.SerdeInfo != nil {
			f6f10 := &svcsdktypes.SerDeInfo{}
			if r.ko.Spec.StorageDescriptor.SerdeInfo.Name != nil {
				f6f10.Name = r.ko.Spec.StorageDescriptor.SerdeInfo.Name
			}
			if r.ko.Spec.StorageDescriptor.SerdeInfo.Parameters != nil {
				f6f10.Parameters = aws.ToStringMap(r.ko.Spec.StorageDescriptor.SerdeInfo.Parameters)
			}
			if r.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary != nil {
				f6f10.SerializationLibrary = r.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary
			}
			f6.SerdeInfo = f6f10
		}
		if r.ko.Spec.StorageDescriptor.SkewedInfo != nil {
			f6f11 := &svcsdktypes.SkewedInfo{}
			if r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames != nil {
				f6f11.SkewedColumnNames = aws.ToStringSlice(r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames)
			}
			if r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps != nil {
				f6f11.SkewedColumnValueLocationMaps = aws.ToStringMap(r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps)
			}
			if r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues != nil {
				f6f11.SkewedColumnValues = aws.ToStringSlice(r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues)
			}
			f6.SkewedInfo = f6f11
		}
		if r.ko.Spec.StorageDescriptor.SortColumns != nil {
			f6f12 := []svcsdktypes.Order{}
			for _, f6f12iter := range r.ko.Spec.StorageDescriptor.SortColumns {
				f6f12elem := &svcsdktypes.Order{}
				if f6f12iter.Column != nil {
					f6f12elem.Column = f6f12iter.Column
				}
				if f6f12iter.SortOrder != nil {
					sortOrderCopy0 := *f6f12iter.SortOrder
					if sortOrderCopy0 > math.MaxInt32 || sortOrderCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field SortOrder is of type int32")
					}
					sortOrderCopy := int32(sortOrderCopy0)
					f6f12elem.SortOrder = sortOrderCopy
				}
				f6f12 = append(f6f12, *f6f12elem)
			}
			f6.SortColumns = f6f12
		}
		if r.ko.Spec.StorageDescriptor.StoredAsSubDirectories != nil {
			f6.StoredAsSubDirectories = *r.ko.Spec.StorageDescriptor.StoredAsSubDirectories
		}
		fw.StorageDescriptor = f6
	}
	if r.ko.Spec.TableType != nil {
		fw.TableType = r.ko.Spec.TableType
	}
	if r.ko.Spec.TargetTable != nil {
		f8 := &svcsdktypes.TableIdentifier{}
		if r.ko.Spec.TargetTable.CatalogID != nil {
			f8.CatalogId = r.ko.Spec.TargetTable.CatalogID
		}
		if r.ko.Spec.TargetTable.DatabaseName != nil {
			f8.DatabaseName = r.ko.Spec.TargetTable.DatabaseName
		}
		if r.ko.Spec.TargetTable.Name != nil {
			f8.Name = r.ko.Spec.TargetTable.Name
		}
		if r.ko.Spec.TargetTable.Region != nil {
			f8.Region = r.ko.Spec.TargetTable.Region
		}
		fw.TargetTable = f8
	}
	if r.ko.Spec.ViewExpandedText != nil {
		fw.ViewExpandedText = r.ko.Spec.ViewExpandedText
	}
	if r.ko.Spec.ViewOriginalText != nil {
		fw.ViewOriginalText = r.ko.Spec.ViewOriginalText
	}
	res.TableInput = fw

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	input.CatalogId = desired.ko.Spec.CatalogID
	input.DatabaseName = desired.ko.Spec.DatabaseName

	var resp *svcsdk.UpdateTableOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateTable(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateTable", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateTableInput, error) {
	res := &svcsdk.UpdateTableInput{}

	fw := &svcsdktypes.TableInput{}
	if r.ko.Spec.Description != nil {
		fw.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.Name != nil {
		fw.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Owner != nil {
		fw.Owner = r.ko.Spec.Owner
	}
	if r.ko.Spec.Parameters != nil {
		fw.Parameters = aws.ToStringMap(r.ko.Spec.Parameters)
	}
	if r.ko.Spec.PartitionKeys != nil {
		f4 := []svcsdktypes.Column{}
		for _, f4iter := range r.ko.Spec.PartitionKeys {
			f4elem := &svcsdktypes.Column{}
			if f4iter.Comment != nil {
				f4elem.Comment = f4iter.Comment
			}
			if f4iter.Name != nil {
				f4elem.Name = f4iter.Name
			}
			if f4iter.Parameters != nil {
				f4elem.Parameters = aws.ToStringMap(f4iter.Parameters)
			}
			if f4iter.Type != nil {
				f4elem.Type = f4iter.Type
			}
			f4 = append(f4, *f4elem)
		}
		fw.PartitionKeys = f4
	}
	if r.ko.Spec.Retention != nil {
		retentionCopy0 := *r.ko.Spec.Retention
		if retentionCopy0 > math.MaxInt32 || retentionCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Retention is of type int32")
		}
		retentionCopy := int32(retentionCopy0)
		fw.Retention = retentionCopy
	}
	if r.ko.Spec.StorageDescriptor != nil {
		f6 := &svcsdktypes.StorageDescriptor{}
		if r.ko.Spec.StorageDescriptor.AdditionalLocations != nil {
			f6.AdditionalLocations = aws.ToStringSlice(r.ko.Spec.StorageDescriptor.AdditionalLocations)
		}
		if r.ko.Spec.StorageDescriptor.BucketColumns != nil {
			f6.BucketColumns = aws.ToStringSlice(r.ko.Spec.StorageDescriptor.BucketColumns)
		}
		if r.ko.Spec.StorageDescriptor.Columns != nil {
			f6f2 := []svcsdktypes.Column{}
			for _, f6f2iter := range r.ko.Spec.StorageDescriptor.Columns {
				f6f2elem := &svcsdktypes.Column{}
				if f6f2iter.Comment != nil {
					f6f2elem.Comment = f6f2iter.Comment
				}
				if f6f2iter.Name != nil {
					f6f2elem.Name = f6f2iter.Name
				}
				if f6f2iter.Parameters != nil {
					f6f2elem.Parameters = aws.ToStringMap(f6f2iter.Parameters)
				}
				if f6f2iter.Type != nil {
					f6f2elem.Type = f6f2iter.Type
				}
				f6f2 = append(f6f2, *f6f2elem)
			}
			f6.Columns = f6f2
		}
		if r.ko.Spec.StorageDescriptor.Compressed != nil {
			f6.Compressed = *r.ko.Spec.StorageDescriptor.Compressed
		}
		if r.ko.Spec.StorageDescriptor.InputFormat != nil {
			f6.InputFormat = r.ko.Spec.StorageDescriptor.InputFormat
		}
		if r.ko.Spec.StorageDescriptor.Location != nil {
			f6.Location = r.ko.Spec.StorageDescriptor.Location
		}
		if r.ko.Spec.StorageDescriptor.NumberOfBuckets != nil {
			numberOfBucketsCopy0 := *r.ko.Spec.StorageDescriptor.NumberOfBuckets
			if numberOfBucketsCopy0 > math.MaxInt32 || numberOfBucketsCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field NumberOfBuckets is of type int32")
			}
			numberOfBucketsCopy := int32(numberOfBucketsCopy0)
			f6.NumberOfBuckets = numberOfBucketsCopy
		}
		if r.ko.Spec.StorageDescriptor.OutputFormat != nil {
			f6.OutputFormat = r.ko.Spec.StorageDescriptor.OutputFormat
		}
		if r.ko.Spec.StorageDescriptor.Parameters != nil {
			f6.Parameters = aws.ToStringMap(r.ko.Spec.StorageDescriptor.Parameters)
		}
		if r.ko.Spec.StorageDescriptor.SchemaReference != nil {
			f6f9 := &svcsdktypes.SchemaReference{}
			if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID != nil {
				f6f9f0 := &svcsdktypes.SchemaId{}
				if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName != nil {
					f6f9f0.RegistryName = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.RegistryName
				}
				if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN != nil {
					f6f9f0.SchemaArn = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaARN
				}
				if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName != nil {
					f6f9f0.SchemaName = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaID.SchemaName
				}
				f6f9.SchemaId = f6f9f0
			}
			if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID != nil {
				f6f9.SchemaVersionId = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionID
			}
			if r.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber != nil {
				f6f9.SchemaVersionNumber = r.ko.Spec.StorageDescriptor.SchemaReference.SchemaVersionNumber
			}
			f6.SchemaReference = f6f9
		}
		if r.ko.Spec.StorageDescriptor.SerdeInfo != nil {
			f6f10 := &svcsdktypes.SerDeInfo{}
			if r.ko.Spec.StorageDescriptor.SerdeInfo.Name != nil {
				f6f10.Name = r.ko.Spec.StorageDescriptor.SerdeInfo.Name
			}
			if r.ko.Spec.StorageDescriptor.SerdeInfo.Parameters != nil {
				f6f10.Parameters = aws.ToStringMap(r.ko.Spec.StorageDescriptor.SerdeInfo.Parameters)
			}
			if r.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary != nil {
				f6f10.SerializationLibrary = r.ko.Spec.StorageDescriptor.SerdeInfo.SerializationLibrary
			}
			f6.SerdeInfo = f6f10
		}
		if r.ko.Spec.StorageDescriptor.SkewedInfo != nil {
			f6f11 := &svcsdktypes.SkewedInfo{}
			if r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames != nil {
				f6f11.SkewedColumnNames = aws.ToStringSlice(r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnNames)
			}
			if r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps != nil {
				f6f11.SkewedColumnValueLocationMaps = aws.ToStringMap(r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValueLocationMaps)
			}
			if r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues != nil {
				f6f11.SkewedColumnValues = aws.ToStringSlice(r.ko.Spec.StorageDescriptor.SkewedInfo.SkewedColumnValues)
			}
			f6.SkewedInfo = f6f11
		}
		if r.ko.Spec.StorageDescriptor.SortColumns != nil {
			f6f12 := []svcsdktypes.Order{}
			for _, f6f12iter := range r.ko.Spec.StorageDescriptor.SortColumns {
				f6f12elem := &svcsdktypes.Order{}
				if f6f12iter.Column != nil {
					f6f12elem.Column = f6f12iter.Column
				}
				if f6f12iter.SortOrder != nil {
					sortOrderCopy0 := *f6f12iter.SortOrder
					if sortOrderCopy0 > math.MaxInt32 || sortOrderCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field SortOrder is of type int32")
					}
					sortOrderCopy := int32(sortOrderCopy0)
					f6f12elem.SortOrder = sortOrderCopy
				}
				f6f12 = append(f6f12, *f6f12elem)
			}
			f6.SortColumns = f6f12
		}
		if r.ko.Spec.StorageDescriptor.StoredAsSubDirectories != nil {
			f6.StoredAsSubDirectories = *r.ko.Spec.StorageDescriptor.StoredAsSubDirectories
		}
		fw.StorageDescriptor = f6
	}
	if r.ko.Spec.TableType != nil {
		fw.TableType = r.ko.Spec.TableType
	}
	if r.ko.Spec.TargetTable != nil {
		f8 := &svcsdktypes.TableIdentifier{}
		if r.ko.Spec.TargetTable.CatalogID != nil {
			f8.CatalogId = r.ko.Spec.TargetTable.CatalogID
		}
		if r.ko.Spec.TargetTable.DatabaseName != nil {
			f8.DatabaseName = r.ko.Spec.TargetTable.DatabaseName
		}
		if r.ko.Spec.TargetTable.Name != nil {
			f8.Name = r.ko.Spec.TargetTable.Name
		}
		if r.ko.Spec.TargetTable.Region != nil {
			f8.Region = r.ko.Spec.TargetTable.Region
		}
		fw.TargetTable = f8
	}
	if r.ko.Spec.ViewExpandedText != nil {
		fw.ViewExpandedText = r.ko.Spec.ViewExpandedText
	}
	if r.ko.Spec.ViewOriginalText != nil {
		fw.ViewOriginalText = r.ko.Spec.ViewOriginalText
	}
	res.TableInput = fw

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteTableOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteTable(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteTable", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteTableInput, error) {
	res := &svcsdk.DeleteTableInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.DatabaseName != nil {
		res.DatabaseName = r.ko.Spec.DatabaseName
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Table,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidInputException":
		return true
	default:
		return false
	}
}
