// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AdditionalOptionKeys string

const (
	AdditionalOptionKeys_observations_scope        AdditionalOptionKeys = "observations.scope"
	AdditionalOptionKeys_performanceTuning_caching AdditionalOptionKeys = "performanceTuning.caching"
)

type AggFunction string

const (
	AggFunction_avg           AggFunction = "avg"
	AggFunction_count         AggFunction = "count"
	AggFunction_countDistinct AggFunction = "countDistinct"
	AggFunction_first         AggFunction = "first"
	AggFunction_kurtosis      AggFunction = "kurtosis"
	AggFunction_last          AggFunction = "last"
	AggFunction_max           AggFunction = "max"
	AggFunction_min           AggFunction = "min"
	AggFunction_skewness      AggFunction = "skewness"
	AggFunction_stddev_pop    AggFunction = "stddev_pop"
	AggFunction_stddev_samp   AggFunction = "stddev_samp"
	AggFunction_sum           AggFunction = "sum"
	AggFunction_sumDistinct   AggFunction = "sumDistinct"
	AggFunction_var_pop       AggFunction = "var_pop"
	AggFunction_var_samp      AggFunction = "var_samp"
)

type AuthenticationType string

const (
	AuthenticationType_BASIC  AuthenticationType = "BASIC"
	AuthenticationType_CUSTOM AuthenticationType = "CUSTOM"
	AuthenticationType_OAUTH2 AuthenticationType = "OAUTH2"
)

type BackfillErrorCode string

const (
	BackfillErrorCode_ENCRYPTED_PARTITION_ERROR             BackfillErrorCode = "ENCRYPTED_PARTITION_ERROR"
	BackfillErrorCode_INTERNAL_ERROR                        BackfillErrorCode = "INTERNAL_ERROR"
	BackfillErrorCode_INVALID_PARTITION_TYPE_DATA_ERROR     BackfillErrorCode = "INVALID_PARTITION_TYPE_DATA_ERROR"
	BackfillErrorCode_MISSING_PARTITION_VALUE_ERROR         BackfillErrorCode = "MISSING_PARTITION_VALUE_ERROR"
	BackfillErrorCode_UNSUPPORTED_PARTITION_CHARACTER_ERROR BackfillErrorCode = "UNSUPPORTED_PARTITION_CHARACTER_ERROR"
)

type BlueprintRunState string

const (
	BlueprintRunState_FAILED       BlueprintRunState = "FAILED"
	BlueprintRunState_ROLLING_BACK BlueprintRunState = "ROLLING_BACK"
	BlueprintRunState_RUNNING      BlueprintRunState = "RUNNING"
	BlueprintRunState_SUCCEEDED    BlueprintRunState = "SUCCEEDED"
)

type BlueprintStatus string

const (
	BlueprintStatus_ACTIVE   BlueprintStatus = "ACTIVE"
	BlueprintStatus_CREATING BlueprintStatus = "CREATING"
	BlueprintStatus_FAILED   BlueprintStatus = "FAILED"
	BlueprintStatus_UPDATING BlueprintStatus = "UPDATING"
)

type CatalogEncryptionMode string

const (
	CatalogEncryptionMode_DISABLED                  CatalogEncryptionMode = "DISABLED"
	CatalogEncryptionMode_SSE_KMS                   CatalogEncryptionMode = "SSE-KMS"
	CatalogEncryptionMode_SSE_KMS_WITH_SERVICE_ROLE CatalogEncryptionMode = "SSE-KMS-WITH-SERVICE-ROLE"
)

type CloudWatchEncryptionMode string

const (
	CloudWatchEncryptionMode_DISABLED CloudWatchEncryptionMode = "DISABLED"
	CloudWatchEncryptionMode_SSE_KMS  CloudWatchEncryptionMode = "SSE-KMS"
)

type ColumnStatisticsState string

const (
	ColumnStatisticsState_FAILED    ColumnStatisticsState = "FAILED"
	ColumnStatisticsState_RUNNING   ColumnStatisticsState = "RUNNING"
	ColumnStatisticsState_STARTING  ColumnStatisticsState = "STARTING"
	ColumnStatisticsState_STOPPED   ColumnStatisticsState = "STOPPED"
	ColumnStatisticsState_SUCCEEDED ColumnStatisticsState = "SUCCEEDED"
)

type ColumnStatisticsType string

const (
	ColumnStatisticsType_BINARY  ColumnStatisticsType = "BINARY"
	ColumnStatisticsType_BOOLEAN ColumnStatisticsType = "BOOLEAN"
	ColumnStatisticsType_DATE    ColumnStatisticsType = "DATE"
	ColumnStatisticsType_DECIMAL ColumnStatisticsType = "DECIMAL"
	ColumnStatisticsType_DOUBLE  ColumnStatisticsType = "DOUBLE"
	ColumnStatisticsType_LONG    ColumnStatisticsType = "LONG"
	ColumnStatisticsType_STRING  ColumnStatisticsType = "STRING"
)

type Comparator string

const (
	Comparator_EQUALS              Comparator = "EQUALS"
	Comparator_GREATER_THAN        Comparator = "GREATER_THAN"
	Comparator_GREATER_THAN_EQUALS Comparator = "GREATER_THAN_EQUALS"
	Comparator_LESS_THAN           Comparator = "LESS_THAN"
	Comparator_LESS_THAN_EQUALS    Comparator = "LESS_THAN_EQUALS"
)

type Compatibility string

const (
	Compatibility_BACKWARD     Compatibility = "BACKWARD"
	Compatibility_BACKWARD_ALL Compatibility = "BACKWARD_ALL"
	Compatibility_DISABLED     Compatibility = "DISABLED"
	Compatibility_FORWARD      Compatibility = "FORWARD"
	Compatibility_FORWARD_ALL  Compatibility = "FORWARD_ALL"
	Compatibility_FULL         Compatibility = "FULL"
	Compatibility_FULL_ALL     Compatibility = "FULL_ALL"
	Compatibility_NONE         Compatibility = "NONE"
)

type CompressionType string

const (
	CompressionType_bzip2 CompressionType = "bzip2"
	CompressionType_gzip  CompressionType = "gzip"
)

type ComputationType string

const (
	ComputationType_FULL        ComputationType = "FULL"
	ComputationType_INCREMENTAL ComputationType = "INCREMENTAL"
)

type ConnectionPropertyKey string

const (
	ConnectionPropertyKey_CLUSTER_IDENTIFIER                       ConnectionPropertyKey = "CLUSTER_IDENTIFIER"
	ConnectionPropertyKey_CONFIG_FILES                             ConnectionPropertyKey = "CONFIG_FILES"
	ConnectionPropertyKey_CONNECTION_URL                           ConnectionPropertyKey = "CONNECTION_URL"
	ConnectionPropertyKey_CONNECTOR_CLASS_NAME                     ConnectionPropertyKey = "CONNECTOR_CLASS_NAME"
	ConnectionPropertyKey_CONNECTOR_TYPE                           ConnectionPropertyKey = "CONNECTOR_TYPE"
	ConnectionPropertyKey_CONNECTOR_URL                            ConnectionPropertyKey = "CONNECTOR_URL"
	ConnectionPropertyKey_CUSTOM_JDBC_CERT                         ConnectionPropertyKey = "CUSTOM_JDBC_CERT"
	ConnectionPropertyKey_CUSTOM_JDBC_CERT_STRING                  ConnectionPropertyKey = "CUSTOM_JDBC_CERT_STRING"
	ConnectionPropertyKey_DATABASE                                 ConnectionPropertyKey = "DATABASE"
	ConnectionPropertyKey_ENCRYPTED_KAFKA_CLIENT_KEYSTORE_PASSWORD ConnectionPropertyKey = "ENCRYPTED_KAFKA_CLIENT_KEYSTORE_PASSWORD"
	ConnectionPropertyKey_ENCRYPTED_KAFKA_CLIENT_KEY_PASSWORD      ConnectionPropertyKey = "ENCRYPTED_KAFKA_CLIENT_KEY_PASSWORD"
	ConnectionPropertyKey_ENCRYPTED_KAFKA_SASL_PLAIN_PASSWORD      ConnectionPropertyKey = "ENCRYPTED_KAFKA_SASL_PLAIN_PASSWORD"
	ConnectionPropertyKey_ENCRYPTED_KAFKA_SASL_SCRAM_PASSWORD      ConnectionPropertyKey = "ENCRYPTED_KAFKA_SASL_SCRAM_PASSWORD"
	ConnectionPropertyKey_ENCRYPTED_PASSWORD                       ConnectionPropertyKey = "ENCRYPTED_PASSWORD"
	ConnectionPropertyKey_HOST                                     ConnectionPropertyKey = "HOST"
	ConnectionPropertyKey_INSTANCE_ID                              ConnectionPropertyKey = "INSTANCE_ID"
	ConnectionPropertyKey_JDBC_CONNECTION_URL                      ConnectionPropertyKey = "JDBC_CONNECTION_URL"
	ConnectionPropertyKey_JDBC_DRIVER_CLASS_NAME                   ConnectionPropertyKey = "JDBC_DRIVER_CLASS_NAME"
	ConnectionPropertyKey_JDBC_DRIVER_JAR_URI                      ConnectionPropertyKey = "JDBC_DRIVER_JAR_URI"
	ConnectionPropertyKey_JDBC_ENFORCE_SSL                         ConnectionPropertyKey = "JDBC_ENFORCE_SSL"
	ConnectionPropertyKey_JDBC_ENGINE                              ConnectionPropertyKey = "JDBC_ENGINE"
	ConnectionPropertyKey_JDBC_ENGINE_VERSION                      ConnectionPropertyKey = "JDBC_ENGINE_VERSION"
	ConnectionPropertyKey_KAFKA_BOOTSTRAP_SERVERS                  ConnectionPropertyKey = "KAFKA_BOOTSTRAP_SERVERS"
	ConnectionPropertyKey_KAFKA_CLIENT_KEYSTORE                    ConnectionPropertyKey = "KAFKA_CLIENT_KEYSTORE"
	ConnectionPropertyKey_KAFKA_CLIENT_KEYSTORE_PASSWORD           ConnectionPropertyKey = "KAFKA_CLIENT_KEYSTORE_PASSWORD"
	ConnectionPropertyKey_KAFKA_CLIENT_KEY_PASSWORD                ConnectionPropertyKey = "KAFKA_CLIENT_KEY_PASSWORD"
	ConnectionPropertyKey_KAFKA_CUSTOM_CERT                        ConnectionPropertyKey = "KAFKA_CUSTOM_CERT"
	ConnectionPropertyKey_KAFKA_SASL_GSSAPI_KEYTAB                 ConnectionPropertyKey = "KAFKA_SASL_GSSAPI_KEYTAB"
	ConnectionPropertyKey_KAFKA_SASL_GSSAPI_KRB5_CONF              ConnectionPropertyKey = "KAFKA_SASL_GSSAPI_KRB5_CONF"
	ConnectionPropertyKey_KAFKA_SASL_GSSAPI_PRINCIPAL              ConnectionPropertyKey = "KAFKA_SASL_GSSAPI_PRINCIPAL"
	ConnectionPropertyKey_KAFKA_SASL_GSSAPI_SERVICE                ConnectionPropertyKey = "KAFKA_SASL_GSSAPI_SERVICE"
	ConnectionPropertyKey_KAFKA_SASL_MECHANISM                     ConnectionPropertyKey = "KAFKA_SASL_MECHANISM"
	ConnectionPropertyKey_KAFKA_SASL_PLAIN_PASSWORD                ConnectionPropertyKey = "KAFKA_SASL_PLAIN_PASSWORD"
	ConnectionPropertyKey_KAFKA_SASL_PLAIN_USERNAME                ConnectionPropertyKey = "KAFKA_SASL_PLAIN_USERNAME"
	ConnectionPropertyKey_KAFKA_SASL_SCRAM_PASSWORD                ConnectionPropertyKey = "KAFKA_SASL_SCRAM_PASSWORD"
	ConnectionPropertyKey_KAFKA_SASL_SCRAM_SECRETS_ARN             ConnectionPropertyKey = "KAFKA_SASL_SCRAM_SECRETS_ARN"
	ConnectionPropertyKey_KAFKA_SASL_SCRAM_USERNAME                ConnectionPropertyKey = "KAFKA_SASL_SCRAM_USERNAME"
	ConnectionPropertyKey_KAFKA_SKIP_CUSTOM_CERT_VALIDATION        ConnectionPropertyKey = "KAFKA_SKIP_CUSTOM_CERT_VALIDATION"
	ConnectionPropertyKey_KAFKA_SSL_ENABLED                        ConnectionPropertyKey = "KAFKA_SSL_ENABLED"
	ConnectionPropertyKey_PASSWORD                                 ConnectionPropertyKey = "PASSWORD"
	ConnectionPropertyKey_PORT                                     ConnectionPropertyKey = "PORT"
	ConnectionPropertyKey_REGION                                   ConnectionPropertyKey = "REGION"
	ConnectionPropertyKey_ROLE_ARN                                 ConnectionPropertyKey = "ROLE_ARN"
	ConnectionPropertyKey_SECRET_ID                                ConnectionPropertyKey = "SECRET_ID"
	ConnectionPropertyKey_SKIP_CUSTOM_JDBC_CERT_VALIDATION         ConnectionPropertyKey = "SKIP_CUSTOM_JDBC_CERT_VALIDATION"
	ConnectionPropertyKey_USERNAME                                 ConnectionPropertyKey = "USERNAME"
	ConnectionPropertyKey_WORKGROUP_NAME                           ConnectionPropertyKey = "WORKGROUP_NAME"
)

type ConnectionStatus string

const (
	ConnectionStatus_FAILED      ConnectionStatus = "FAILED"
	ConnectionStatus_IN_PROGRESS ConnectionStatus = "IN_PROGRESS"
	ConnectionStatus_READY       ConnectionStatus = "READY"
)

type ConnectionType string

const (
	ConnectionType_CUSTOM                   ConnectionType = "CUSTOM"
	ConnectionType_JDBC                     ConnectionType = "JDBC"
	ConnectionType_KAFKA                    ConnectionType = "KAFKA"
	ConnectionType_MARKETPLACE              ConnectionType = "MARKETPLACE"
	ConnectionType_MONGODB                  ConnectionType = "MONGODB"
	ConnectionType_NETWORK                  ConnectionType = "NETWORK"
	ConnectionType_SALESFORCE               ConnectionType = "SALESFORCE"
	ConnectionType_SFTP                     ConnectionType = "SFTP"
	ConnectionType_VIEW_VALIDATION_ATHENA   ConnectionType = "VIEW_VALIDATION_ATHENA"
	ConnectionType_VIEW_VALIDATION_REDSHIFT ConnectionType = "VIEW_VALIDATION_REDSHIFT"
)

type CrawlState string

const (
	CrawlState_CANCELLED  CrawlState = "CANCELLED"
	CrawlState_CANCELLING CrawlState = "CANCELLING"
	CrawlState_ERROR      CrawlState = "ERROR"
	CrawlState_FAILED     CrawlState = "FAILED"
	CrawlState_RUNNING    CrawlState = "RUNNING"
	CrawlState_SUCCEEDED  CrawlState = "SUCCEEDED"
)

type CrawlerHistoryState string

const (
	CrawlerHistoryState_COMPLETED CrawlerHistoryState = "COMPLETED"
	CrawlerHistoryState_FAILED    CrawlerHistoryState = "FAILED"
	CrawlerHistoryState_RUNNING   CrawlerHistoryState = "RUNNING"
	CrawlerHistoryState_STOPPED   CrawlerHistoryState = "STOPPED"
)

type CrawlerLineageSettings string

const (
	CrawlerLineageSettings_DISABLE CrawlerLineageSettings = "DISABLE"
	CrawlerLineageSettings_ENABLE  CrawlerLineageSettings = "ENABLE"
)

type CrawlerState string

const (
	CrawlerState_READY    CrawlerState = "READY"
	CrawlerState_RUNNING  CrawlerState = "RUNNING"
	CrawlerState_STOPPING CrawlerState = "STOPPING"
)

type CsvHeaderOption string

const (
	CsvHeaderOption_ABSENT  CsvHeaderOption = "ABSENT"
	CsvHeaderOption_PRESENT CsvHeaderOption = "PRESENT"
	CsvHeaderOption_UNKNOWN CsvHeaderOption = "UNKNOWN"
)

type CsvSerdeOption string

const (
	CsvSerdeOption_LazySimpleSerDe CsvSerdeOption = "LazySimpleSerDe"
	CsvSerdeOption_None            CsvSerdeOption = "None"
	CsvSerdeOption_OpenCSVSerDe    CsvSerdeOption = "OpenCSVSerDe"
)

type DQCompositeRuleEvaluationMethod string

const (
	DQCompositeRuleEvaluationMethod_COLUMN DQCompositeRuleEvaluationMethod = "COLUMN"
	DQCompositeRuleEvaluationMethod_ROW    DQCompositeRuleEvaluationMethod = "ROW"
)

type DQStopJobOnFailureTiming string

const (
	DQStopJobOnFailureTiming_AfterDataLoad DQStopJobOnFailureTiming = "AfterDataLoad"
	DQStopJobOnFailureTiming_Immediate     DQStopJobOnFailureTiming = "Immediate"
)

type DQTransformOutput string

const (
	DQTransformOutput_EvaluationResults DQTransformOutput = "EvaluationResults"
	DQTransformOutput_PrimaryInput      DQTransformOutput = "PrimaryInput"
)

type DataFormat string

const (
	DataFormat_AVRO     DataFormat = "AVRO"
	DataFormat_JSON     DataFormat = "JSON"
	DataFormat_PROTOBUF DataFormat = "PROTOBUF"
)

type DataQualityModelStatus string

const (
	DataQualityModelStatus_FAILED    DataQualityModelStatus = "FAILED"
	DataQualityModelStatus_RUNNING   DataQualityModelStatus = "RUNNING"
	DataQualityModelStatus_SUCCEEDED DataQualityModelStatus = "SUCCEEDED"
)

type DataQualityRuleResultStatus string

const (
	DataQualityRuleResultStatus_ERROR DataQualityRuleResultStatus = "ERROR"
	DataQualityRuleResultStatus_FAIL  DataQualityRuleResultStatus = "FAIL"
	DataQualityRuleResultStatus_PASS  DataQualityRuleResultStatus = "PASS"
)

type DatabaseAttributes string

const (
	DatabaseAttributes_NAME DatabaseAttributes = "NAME"
)

type DeleteBehavior string

const (
	DeleteBehavior_DELETE_FROM_DATABASE  DeleteBehavior = "DELETE_FROM_DATABASE"
	DeleteBehavior_DEPRECATE_IN_DATABASE DeleteBehavior = "DEPRECATE_IN_DATABASE"
	DeleteBehavior_LOG                   DeleteBehavior = "LOG"
)

type DeltaTargetCompressionType string

const (
	DeltaTargetCompressionType_snappy       DeltaTargetCompressionType = "snappy"
	DeltaTargetCompressionType_uncompressed DeltaTargetCompressionType = "uncompressed"
)

type EnableHybridValues string

const (
	EnableHybridValues_FALSE EnableHybridValues = "FALSE"
	EnableHybridValues_TRUE  EnableHybridValues = "TRUE"
)

type ExecutionClass string

const (
	ExecutionClass_FLEX     ExecutionClass = "FLEX"
	ExecutionClass_STANDARD ExecutionClass = "STANDARD"
)

type ExistCondition string

const (
	ExistCondition_MUST_EXIST ExistCondition = "MUST_EXIST"
	ExistCondition_NONE       ExistCondition = "NONE"
	ExistCondition_NOT_EXIST  ExistCondition = "NOT_EXIST"
)

type FederationSourceErrorCode string

const (
	FederationSourceErrorCode_AccessDeniedException          FederationSourceErrorCode = "AccessDeniedException"
	FederationSourceErrorCode_EntityNotFoundException        FederationSourceErrorCode = "EntityNotFoundException"
	FederationSourceErrorCode_InternalServiceException       FederationSourceErrorCode = "InternalServiceException"
	FederationSourceErrorCode_InvalidCredentialsException    FederationSourceErrorCode = "InvalidCredentialsException"
	FederationSourceErrorCode_InvalidInputException          FederationSourceErrorCode = "InvalidInputException"
	FederationSourceErrorCode_InvalidResponseException       FederationSourceErrorCode = "InvalidResponseException"
	FederationSourceErrorCode_OperationNotSupportedException FederationSourceErrorCode = "OperationNotSupportedException"
	FederationSourceErrorCode_OperationTimeoutException      FederationSourceErrorCode = "OperationTimeoutException"
	FederationSourceErrorCode_PartialFailureException        FederationSourceErrorCode = "PartialFailureException"
	FederationSourceErrorCode_ThrottlingException            FederationSourceErrorCode = "ThrottlingException"
)

type FieldName string

const (
	FieldName_CRAWL_ID   FieldName = "CRAWL_ID"
	FieldName_DPU_HOUR   FieldName = "DPU_HOUR"
	FieldName_END_TIME   FieldName = "END_TIME"
	FieldName_START_TIME FieldName = "START_TIME"
	FieldName_STATE      FieldName = "STATE"
)

type FilterLogicalOperator string

const (
	FilterLogicalOperator_AND FilterLogicalOperator = "AND"
	FilterLogicalOperator_OR  FilterLogicalOperator = "OR"
)

type FilterOperation string

const (
	FilterOperation_EQ     FilterOperation = "EQ"
	FilterOperation_GT     FilterOperation = "GT"
	FilterOperation_GTE    FilterOperation = "GTE"
	FilterOperation_ISNULL FilterOperation = "ISNULL"
	FilterOperation_LT     FilterOperation = "LT"
	FilterOperation_LTE    FilterOperation = "LTE"
	FilterOperation_REGEX  FilterOperation = "REGEX"
)

type FilterOperator string

const (
	FilterOperator_EQ FilterOperator = "EQ"
	FilterOperator_GE FilterOperator = "GE"
	FilterOperator_GT FilterOperator = "GT"
	FilterOperator_LE FilterOperator = "LE"
	FilterOperator_LT FilterOperator = "LT"
	FilterOperator_NE FilterOperator = "NE"
)

type FilterValueType string

const (
	FilterValueType_COLUMNEXTRACTED FilterValueType = "COLUMNEXTRACTED"
	FilterValueType_CONSTANT        FilterValueType = "CONSTANT"
)

type GlueRecordType string

const (
	GlueRecordType_BIGDECIMAL GlueRecordType = "BIGDECIMAL"
	GlueRecordType_BYTE       GlueRecordType = "BYTE"
	GlueRecordType_DATE       GlueRecordType = "DATE"
	GlueRecordType_DOUBLE     GlueRecordType = "DOUBLE"
	GlueRecordType_FLOAT      GlueRecordType = "FLOAT"
	GlueRecordType_INT        GlueRecordType = "INT"
	GlueRecordType_LONG       GlueRecordType = "LONG"
	GlueRecordType_SHORT      GlueRecordType = "SHORT"
	GlueRecordType_STRING     GlueRecordType = "STRING"
	GlueRecordType_TIMESTAMP  GlueRecordType = "TIMESTAMP"
)

type HudiTargetCompressionType string

const (
	HudiTargetCompressionType_gzip         HudiTargetCompressionType = "gzip"
	HudiTargetCompressionType_lzo          HudiTargetCompressionType = "lzo"
	HudiTargetCompressionType_snappy       HudiTargetCompressionType = "snappy"
	HudiTargetCompressionType_uncompressed HudiTargetCompressionType = "uncompressed"
)

type InclusionAnnotationValue string

const (
	InclusionAnnotationValue_EXCLUDE InclusionAnnotationValue = "EXCLUDE"
	InclusionAnnotationValue_INCLUDE InclusionAnnotationValue = "INCLUDE"
)

type JDBCConnectionType string

const (
	JDBCConnectionType_mysql      JDBCConnectionType = "mysql"
	JDBCConnectionType_oracle     JDBCConnectionType = "oracle"
	JDBCConnectionType_postgresql JDBCConnectionType = "postgresql"
	JDBCConnectionType_redshift   JDBCConnectionType = "redshift"
	JDBCConnectionType_sqlserver  JDBCConnectionType = "sqlserver"
)

type JDBCDataType string

const (
	JDBCDataType_ARRAY                   JDBCDataType = "ARRAY"
	JDBCDataType_BIGINT                  JDBCDataType = "BIGINT"
	JDBCDataType_BINARY                  JDBCDataType = "BINARY"
	JDBCDataType_BIT                     JDBCDataType = "BIT"
	JDBCDataType_BLOB                    JDBCDataType = "BLOB"
	JDBCDataType_BOOLEAN                 JDBCDataType = "BOOLEAN"
	JDBCDataType_CHAR                    JDBCDataType = "CHAR"
	JDBCDataType_CLOB                    JDBCDataType = "CLOB"
	JDBCDataType_DATALINK                JDBCDataType = "DATALINK"
	JDBCDataType_DATE                    JDBCDataType = "DATE"
	JDBCDataType_DECIMAL                 JDBCDataType = "DECIMAL"
	JDBCDataType_DISTINCT                JDBCDataType = "DISTINCT"
	JDBCDataType_DOUBLE                  JDBCDataType = "DOUBLE"
	JDBCDataType_FLOAT                   JDBCDataType = "FLOAT"
	JDBCDataType_INTEGER                 JDBCDataType = "INTEGER"
	JDBCDataType_JAVA_OBJECT             JDBCDataType = "JAVA_OBJECT"
	JDBCDataType_LONGNVARCHAR            JDBCDataType = "LONGNVARCHAR"
	JDBCDataType_LONGVARBINARY           JDBCDataType = "LONGVARBINARY"
	JDBCDataType_LONGVARCHAR             JDBCDataType = "LONGVARCHAR"
	JDBCDataType_NCHAR                   JDBCDataType = "NCHAR"
	JDBCDataType_NCLOB                   JDBCDataType = "NCLOB"
	JDBCDataType_NULL                    JDBCDataType = "NULL"
	JDBCDataType_NUMERIC                 JDBCDataType = "NUMERIC"
	JDBCDataType_NVARCHAR                JDBCDataType = "NVARCHAR"
	JDBCDataType_OTHER                   JDBCDataType = "OTHER"
	JDBCDataType_REAL                    JDBCDataType = "REAL"
	JDBCDataType_REF                     JDBCDataType = "REF"
	JDBCDataType_REF_CURSOR              JDBCDataType = "REF_CURSOR"
	JDBCDataType_ROWID                   JDBCDataType = "ROWID"
	JDBCDataType_SMALLINT                JDBCDataType = "SMALLINT"
	JDBCDataType_SQLXML                  JDBCDataType = "SQLXML"
	JDBCDataType_STRUCT                  JDBCDataType = "STRUCT"
	JDBCDataType_TIME                    JDBCDataType = "TIME"
	JDBCDataType_TIMESTAMP               JDBCDataType = "TIMESTAMP"
	JDBCDataType_TIMESTAMP_WITH_TIMEZONE JDBCDataType = "TIMESTAMP_WITH_TIMEZONE"
	JDBCDataType_TIME_WITH_TIMEZONE      JDBCDataType = "TIME_WITH_TIMEZONE"
	JDBCDataType_TINYINT                 JDBCDataType = "TINYINT"
	JDBCDataType_VARBINARY               JDBCDataType = "VARBINARY"
	JDBCDataType_VARCHAR                 JDBCDataType = "VARCHAR"
)

type JdbcMetadataEntry string

const (
	JdbcMetadataEntry_COMMENTS JdbcMetadataEntry = "COMMENTS"
	JdbcMetadataEntry_RAWTYPES JdbcMetadataEntry = "RAWTYPES"
)

type JobBookmarksEncryptionMode string

const (
	JobBookmarksEncryptionMode_CSE_KMS  JobBookmarksEncryptionMode = "CSE-KMS"
	JobBookmarksEncryptionMode_DISABLED JobBookmarksEncryptionMode = "DISABLED"
)

type JobMode string

const (
	JobMode_NOTEBOOK JobMode = "NOTEBOOK"
	JobMode_SCRIPT   JobMode = "SCRIPT"
	JobMode_VISUAL   JobMode = "VISUAL"
)

type JobRunState string

const (
	JobRunState_ERROR     JobRunState = "ERROR"
	JobRunState_EXPIRED   JobRunState = "EXPIRED"
	JobRunState_FAILED    JobRunState = "FAILED"
	JobRunState_RUNNING   JobRunState = "RUNNING"
	JobRunState_STARTING  JobRunState = "STARTING"
	JobRunState_STOPPED   JobRunState = "STOPPED"
	JobRunState_STOPPING  JobRunState = "STOPPING"
	JobRunState_SUCCEEDED JobRunState = "SUCCEEDED"
	JobRunState_TIMEOUT   JobRunState = "TIMEOUT"
	JobRunState_WAITING   JobRunState = "WAITING"
)

type JoinType string

const (
	JoinType_equijoin JoinType = "equijoin"
	JoinType_left     JoinType = "left"
	JoinType_leftanti JoinType = "leftanti"
	JoinType_leftsemi JoinType = "leftsemi"
	JoinType_outer    JoinType = "outer"
	JoinType_right    JoinType = "right"
)

type Language string

const (
	Language_PYTHON Language = "PYTHON"
	Language_SCALA  Language = "SCALA"
)

type LastCrawlStatus string

const (
	LastCrawlStatus_CANCELLED LastCrawlStatus = "CANCELLED"
	LastCrawlStatus_FAILED    LastCrawlStatus = "FAILED"
	LastCrawlStatus_SUCCEEDED LastCrawlStatus = "SUCCEEDED"
)

type Logical string

const (
	Logical_AND Logical = "AND"
	Logical_ANY Logical = "ANY"
)

type LogicalOperator string

const (
	LogicalOperator_EQUALS LogicalOperator = "EQUALS"
)

type MLUserDataEncryptionModeString string

const (
	MLUserDataEncryptionModeString_DISABLED MLUserDataEncryptionModeString = "DISABLED"
	MLUserDataEncryptionModeString_SSE_KMS  MLUserDataEncryptionModeString = "SSE-KMS"
)

type MetadataOperation string

const (
	MetadataOperation_CREATE MetadataOperation = "CREATE"
)

type NodeType string

const (
	NodeType_CRAWLER NodeType = "CRAWLER"
	NodeType_JOB     NodeType = "JOB"
	NodeType_TRIGGER NodeType = "TRIGGER"
)

type OAuth2GrantType string

const (
	OAuth2GrantType_AUTHORIZATION_CODE OAuth2GrantType = "AUTHORIZATION_CODE"
	OAuth2GrantType_CLIENT_CREDENTIALS OAuth2GrantType = "CLIENT_CREDENTIALS"
	OAuth2GrantType_JWT_BEARER         OAuth2GrantType = "JWT_BEARER"
)

type ParamType string

const (
	ParamType_bool    ParamType = "bool"
	ParamType_complex ParamType = "complex"
	ParamType_float   ParamType = "float"
	ParamType_int     ParamType = "int"
	ParamType_list    ParamType = "list"
	ParamType_null    ParamType = "null"
	ParamType_str     ParamType = "str"
)

type ParquetCompressionType string

const (
	ParquetCompressionType_gzip         ParquetCompressionType = "gzip"
	ParquetCompressionType_lzo          ParquetCompressionType = "lzo"
	ParquetCompressionType_none         ParquetCompressionType = "none"
	ParquetCompressionType_snappy       ParquetCompressionType = "snappy"
	ParquetCompressionType_uncompressed ParquetCompressionType = "uncompressed"
)

type PartitionIndexStatus string

const (
	PartitionIndexStatus_ACTIVE   PartitionIndexStatus = "ACTIVE"
	PartitionIndexStatus_CREATING PartitionIndexStatus = "CREATING"
	PartitionIndexStatus_DELETING PartitionIndexStatus = "DELETING"
	PartitionIndexStatus_FAILED   PartitionIndexStatus = "FAILED"
)

type Permission string

const (
	Permission_ALL                  Permission = "ALL"
	Permission_ALTER                Permission = "ALTER"
	Permission_CREATE_DATABASE      Permission = "CREATE_DATABASE"
	Permission_CREATE_TABLE         Permission = "CREATE_TABLE"
	Permission_DATA_LOCATION_ACCESS Permission = "DATA_LOCATION_ACCESS"
	Permission_DELETE               Permission = "DELETE"
	Permission_DROP                 Permission = "DROP"
	Permission_INSERT               Permission = "INSERT"
	Permission_SELECT               Permission = "SELECT"
)

type PermissionType string

const (
	PermissionType_CELL_FILTER_PERMISSION PermissionType = "CELL_FILTER_PERMISSION"
	PermissionType_COLUMN_PERMISSION      PermissionType = "COLUMN_PERMISSION"
	PermissionType_NESTED_CELL_PERMISSION PermissionType = "NESTED_CELL_PERMISSION"
	PermissionType_NESTED_PERMISSION      PermissionType = "NESTED_PERMISSION"
)

type PiiType string

const (
	PiiType_ColumnAudit   PiiType = "ColumnAudit"
	PiiType_ColumnMasking PiiType = "ColumnMasking"
	PiiType_RowAudit      PiiType = "RowAudit"
	PiiType_RowMasking    PiiType = "RowMasking"
)

type PrincipalType string

const (
	PrincipalType_GROUP PrincipalType = "GROUP"
	PrincipalType_ROLE  PrincipalType = "ROLE"
	PrincipalType_USER  PrincipalType = "USER"
)

type QuoteChar string

const (
	QuoteChar_disabled     QuoteChar = "disabled"
	QuoteChar_quillemet    QuoteChar = "quillemet"
	QuoteChar_quote        QuoteChar = "quote"
	QuoteChar_single_quote QuoteChar = "single_quote"
)

type RECRawlBehavior string

const (
	RECRawlBehavior_CRAWL_EVENT_MODE       RECRawlBehavior = "CRAWL_EVENT_MODE"
	RECRawlBehavior_CRAWL_EVERYTHING       RECRawlBehavior = "CRAWL_EVERYTHING"
	RECRawlBehavior_CRAWL_NEW_FOLDERS_ONLY RECRawlBehavior = "CRAWL_NEW_FOLDERS_ONLY"
)

type RegistryStatus string

const (
	RegistryStatus_AVAILABLE RegistryStatus = "AVAILABLE"
	RegistryStatus_DELETING  RegistryStatus = "DELETING"
)

type ResourceAction string

const (
	ResourceAction_CREATE ResourceAction = "CREATE"
	ResourceAction_UPDATE ResourceAction = "UPDATE"
)

type ResourceShareType string

const (
	ResourceShareType_ALL       ResourceShareType = "ALL"
	ResourceShareType_FEDERATED ResourceShareType = "FEDERATED"
	ResourceShareType_FOREIGN   ResourceShareType = "FOREIGN"
)

type ResourceState string

const (
	ResourceState_FAILED      ResourceState = "FAILED"
	ResourceState_IN_PROGRESS ResourceState = "IN_PROGRESS"
	ResourceState_QUEUED      ResourceState = "QUEUED"
	ResourceState_STOPPED     ResourceState = "STOPPED"
	ResourceState_SUCCESS     ResourceState = "SUCCESS"
)

type ResourceType string

const (
	ResourceType_ARCHIVE ResourceType = "ARCHIVE"
	ResourceType_FILE    ResourceType = "FILE"
	ResourceType_JAR     ResourceType = "JAR"
)

type S3EncryptionMode string

const (
	S3EncryptionMode_DISABLED S3EncryptionMode = "DISABLED"
	S3EncryptionMode_SSE_KMS  S3EncryptionMode = "SSE-KMS"
	S3EncryptionMode_SSE_S3   S3EncryptionMode = "SSE-S3"
)

type ScheduleState string

const (
	ScheduleState_NOT_SCHEDULED ScheduleState = "NOT_SCHEDULED"
	ScheduleState_SCHEDULED     ScheduleState = "SCHEDULED"
	ScheduleState_TRANSITIONING ScheduleState = "TRANSITIONING"
)

type SchemaDiffType string

const (
	SchemaDiffType_SYNTAX_DIFF SchemaDiffType = "SYNTAX_DIFF"
)

type SchemaStatus string

const (
	SchemaStatus_AVAILABLE SchemaStatus = "AVAILABLE"
	SchemaStatus_DELETING  SchemaStatus = "DELETING"
	SchemaStatus_PENDING   SchemaStatus = "PENDING"
)

type SchemaVersionStatus string

const (
	SchemaVersionStatus_AVAILABLE SchemaVersionStatus = "AVAILABLE"
	SchemaVersionStatus_DELETING  SchemaVersionStatus = "DELETING"
	SchemaVersionStatus_FAILURE   SchemaVersionStatus = "FAILURE"
	SchemaVersionStatus_PENDING   SchemaVersionStatus = "PENDING"
)

type Separator string

const (
	Separator_comma     Separator = "comma"
	Separator_ctrla     Separator = "ctrla"
	Separator_pipe      Separator = "pipe"
	Separator_semicolon Separator = "semicolon"
	Separator_tab       Separator = "tab"
)

type SessionStatus string

const (
	SessionStatus_FAILED       SessionStatus = "FAILED"
	SessionStatus_PROVISIONING SessionStatus = "PROVISIONING"
	SessionStatus_READY        SessionStatus = "READY"
	SessionStatus_STOPPED      SessionStatus = "STOPPED"
	SessionStatus_STOPPING     SessionStatus = "STOPPING"
	SessionStatus_TIMEOUT      SessionStatus = "TIMEOUT"
)

type Sort string

const (
	Sort_ASC  Sort = "ASC"
	Sort_DESC Sort = "DESC"
)

type SortDirectionType string

const (
	SortDirectionType_ASCENDING  SortDirectionType = "ASCENDING"
	SortDirectionType_DESCENDING SortDirectionType = "DESCENDING"
)

type SourceControlAuthStrategy string

const (
	SourceControlAuthStrategy_AWS_SECRETS_MANAGER   SourceControlAuthStrategy = "AWS_SECRETS_MANAGER"
	SourceControlAuthStrategy_PERSONAL_ACCESS_TOKEN SourceControlAuthStrategy = "PERSONAL_ACCESS_TOKEN"
)

type SourceControlProvider string

const (
	SourceControlProvider_AWS_CODE_COMMIT SourceControlProvider = "AWS_CODE_COMMIT"
	SourceControlProvider_BITBUCKET       SourceControlProvider = "BITBUCKET"
	SourceControlProvider_GITHUB          SourceControlProvider = "GITHUB"
	SourceControlProvider_GITLAB          SourceControlProvider = "GITLAB"
)

type StartingPosition string

const (
	StartingPosition_earliest     StartingPosition = "earliest"
	StartingPosition_latest       StartingPosition = "latest"
	StartingPosition_timestamp    StartingPosition = "timestamp"
	StartingPosition_trim_horizon StartingPosition = "trim_horizon"
)

type StatementState string

const (
	StatementState_AVAILABLE  StatementState = "AVAILABLE"
	StatementState_CANCELLED  StatementState = "CANCELLED"
	StatementState_CANCELLING StatementState = "CANCELLING"
	StatementState_ERROR      StatementState = "ERROR"
	StatementState_RUNNING    StatementState = "RUNNING"
	StatementState_WAITING    StatementState = "WAITING"
)

type StatisticEvaluationLevel string

const (
	StatisticEvaluationLevel_Column      StatisticEvaluationLevel = "Column"
	StatisticEvaluationLevel_Dataset     StatisticEvaluationLevel = "Dataset"
	StatisticEvaluationLevel_Multicolumn StatisticEvaluationLevel = "Multicolumn"
)

type TableAttributes string

const (
	TableAttributes_NAME       TableAttributes = "NAME"
	TableAttributes_TABLE_TYPE TableAttributes = "TABLE_TYPE"
)

type TableOptimizerEventType string

const (
	TableOptimizerEventType_completed   TableOptimizerEventType = "completed"
	TableOptimizerEventType_failed      TableOptimizerEventType = "failed"
	TableOptimizerEventType_in_progress TableOptimizerEventType = "in_progress"
	TableOptimizerEventType_starting    TableOptimizerEventType = "starting"
)

type TableOptimizerType string

const (
	TableOptimizerType_compaction           TableOptimizerType = "compaction"
	TableOptimizerType_orphan_file_deletion TableOptimizerType = "orphan_file_deletion"
	TableOptimizerType_retention            TableOptimizerType = "retention"
)

type TargetFormat string

const (
	TargetFormat_avro    TargetFormat = "avro"
	TargetFormat_csv     TargetFormat = "csv"
	TargetFormat_delta   TargetFormat = "delta"
	TargetFormat_hudi    TargetFormat = "hudi"
	TargetFormat_json    TargetFormat = "json"
	TargetFormat_orc     TargetFormat = "orc"
	TargetFormat_parquet TargetFormat = "parquet"
)

type TaskRunSortColumnType string

const (
	TaskRunSortColumnType_STARTED       TaskRunSortColumnType = "STARTED"
	TaskRunSortColumnType_STATUS        TaskRunSortColumnType = "STATUS"
	TaskRunSortColumnType_TASK_RUN_TYPE TaskRunSortColumnType = "TASK_RUN_TYPE"
)

type TaskStatusType string

const (
	TaskStatusType_FAILED    TaskStatusType = "FAILED"
	TaskStatusType_RUNNING   TaskStatusType = "RUNNING"
	TaskStatusType_STARTING  TaskStatusType = "STARTING"
	TaskStatusType_STOPPED   TaskStatusType = "STOPPED"
	TaskStatusType_STOPPING  TaskStatusType = "STOPPING"
	TaskStatusType_SUCCEEDED TaskStatusType = "SUCCEEDED"
	TaskStatusType_TIMEOUT   TaskStatusType = "TIMEOUT"
)

type TaskType string

const (
	TaskType_EVALUATION              TaskType = "EVALUATION"
	TaskType_EXPORT_LABELS           TaskType = "EXPORT_LABELS"
	TaskType_FIND_MATCHES            TaskType = "FIND_MATCHES"
	TaskType_IMPORT_LABELS           TaskType = "IMPORT_LABELS"
	TaskType_LABELING_SET_GENERATION TaskType = "LABELING_SET_GENERATION"
)

type TransformSortColumnType string

const (
	TransformSortColumnType_CREATED        TransformSortColumnType = "CREATED"
	TransformSortColumnType_LAST_MODIFIED  TransformSortColumnType = "LAST_MODIFIED"
	TransformSortColumnType_NAME           TransformSortColumnType = "NAME"
	TransformSortColumnType_STATUS         TransformSortColumnType = "STATUS"
	TransformSortColumnType_TRANSFORM_TYPE TransformSortColumnType = "TRANSFORM_TYPE"
)

type TransformStatusType string

const (
	TransformStatusType_DELETING  TransformStatusType = "DELETING"
	TransformStatusType_NOT_READY TransformStatusType = "NOT_READY"
	TransformStatusType_READY     TransformStatusType = "READY"
)

type TransformType string

const (
	TransformType_FIND_MATCHES TransformType = "FIND_MATCHES"
)

type TriggerState string

const (
	TriggerState_ACTIVATED    TriggerState = "ACTIVATED"
	TriggerState_ACTIVATING   TriggerState = "ACTIVATING"
	TriggerState_CREATED      TriggerState = "CREATED"
	TriggerState_CREATING     TriggerState = "CREATING"
	TriggerState_DEACTIVATED  TriggerState = "DEACTIVATED"
	TriggerState_DEACTIVATING TriggerState = "DEACTIVATING"
	TriggerState_DELETING     TriggerState = "DELETING"
	TriggerState_UPDATING     TriggerState = "UPDATING"
)

type TriggerType string

const (
	TriggerType_CONDITIONAL TriggerType = "CONDITIONAL"
	TriggerType_EVENT       TriggerType = "EVENT"
	TriggerType_ON_DEMAND   TriggerType = "ON_DEMAND"
	TriggerType_SCHEDULED   TriggerType = "SCHEDULED"
)

type UnionType string

const (
	UnionType_ALL      UnionType = "ALL"
	UnionType_DISTINCT UnionType = "DISTINCT"
)

type UpdateBehavior string

const (
	UpdateBehavior_LOG                UpdateBehavior = "LOG"
	UpdateBehavior_UPDATE_IN_DATABASE UpdateBehavior = "UPDATE_IN_DATABASE"
)

type UpdateCatalogBehavior string

const (
	UpdateCatalogBehavior_LOG                UpdateCatalogBehavior = "LOG"
	UpdateCatalogBehavior_UPDATE_IN_DATABASE UpdateCatalogBehavior = "UPDATE_IN_DATABASE"
)

type ViewDialect string

const (
	ViewDialect_ATHENA   ViewDialect = "ATHENA"
	ViewDialect_REDSHIFT ViewDialect = "REDSHIFT"
	ViewDialect_SPARK    ViewDialect = "SPARK"
)

type ViewUpdateAction string

const (
	ViewUpdateAction_ADD            ViewUpdateAction = "ADD"
	ViewUpdateAction_ADD_OR_REPLACE ViewUpdateAction = "ADD_OR_REPLACE"
	ViewUpdateAction_DROP           ViewUpdateAction = "DROP"
	ViewUpdateAction_REPLACE        ViewUpdateAction = "REPLACE"
)

type WorkerType string

const (
	WorkerType_G_025X   WorkerType = "G.025X"
	WorkerType_G_1X     WorkerType = "G.1X"
	WorkerType_G_2X     WorkerType = "G.2X"
	WorkerType_G_4X     WorkerType = "G.4X"
	WorkerType_G_8X     WorkerType = "G.8X"
	WorkerType_Standard WorkerType = "Standard"
	WorkerType_Z_2X     WorkerType = "Z.2X"
)

type WorkflowRunStatus string

const (
	WorkflowRunStatus_COMPLETED WorkflowRunStatus = "COMPLETED"
	WorkflowRunStatus_ERROR     WorkflowRunStatus = "ERROR"
	WorkflowRunStatus_RUNNING   WorkflowRunStatus = "RUNNING"
	WorkflowRunStatus_STOPPED   WorkflowRunStatus = "STOPPED"
	WorkflowRunStatus_STOPPING  WorkflowRunStatus = "STOPPING"
)
