// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RegistrySpec defines the desired state of Registry.
//
// Represents an AWS Glue Schema Registry for managing schema versions
// with compatibility rules.
type RegistrySpec struct {

	// The name of the registry. This is a unique identifier for the registry
	// in AWS Glue.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	RegistryName *string `json:"registryName"`

	// A description of the registry. If description is not provided, there will
	// not be any default value for this string.
	// +kubebuilder:validation:MaxLength=2048
	Description *string `json:"description,omitempty"`

	// The compatibility mode for schema evolution in this registry.
	// Valid values are:
	//   - NONE: No compatibility mode applies. You can use this choice in development
	//     scenarios or if you do not know the compatibility mode that you want to apply.
	//     Any new version added will be accepted without undergoing a compatibility check.
	//   - DISABLED: This compatibility choice prevents versioning for a particular schema.
	//     You can use this choice to prevent future versioning of a schema.
	//   - BACKWARD: This compatibility choice is recommended as it allows data receivers
	//     to read both current and previous schema versions. This means that, for instance,
	//     a new schema version cannot drop data fields.
	//   - BACKWARD_ALL: This compatibility choice allows data receivers to read data written
	//     by producers of all previous schema versions. Data receivers must be able to read
	//     data written by producers of all previous schema versions. This means that a new
	//     schema version cannot drop data fields.
	//   - FORWARD: This compatibility choice allows data receivers to read data written by
	//     producers of future schema versions. Data receivers must be able to read data written
	//     by producers of all future schema versions. This means that a new schema version cannot
	//     add data fields that were not present in a previous schema version.
	//   - FORWARD_ALL: This compatibility choice allows data receivers to read data written by
	//     producers of all future schema versions. Data receivers must be able to read data written
	//     by producers of all future schema versions. This means that a new schema version cannot
	//     add data fields that were not present in a previous schema version.
	//   - FULL: This compatibility choice allows data receivers to read both current and previous
	//     schema versions, and allows data receivers to read data written by producers of future
	//     schema versions. This means that a new schema version can neither drop data fields nor add
	//     data fields that were not present in a previous schema version.
	//   - FULL_ALL: This compatibility choice allows data receivers to read data written by producers
	//     of all previous and future schema versions. This means that a new schema version can neither
	//     drop data fields nor add data fields that were not present in a previous schema version.
	// +kubebuilder:validation:Enum=NONE;DISABLED;BACKWARD;FORWARD;FULL;BACKWARD_ALL;FORWARD_ALL;FULL_ALL
	Compatibility *string `json:"compatibility,omitempty"`

	// Determines whether the AWS resource is deleted when the Registry CRD is deleted.
	// Valid values are:
	//   - Delete: The AWS Glue Registry will be deleted when the CRD is deleted
	//   - Retain: The AWS Glue Registry will be retained when the CRD is deleted
	// +kubebuilder:validation:Enum=Delete;Retain
	// +kubebuilder:default=Delete
	DeletionPolicy *string `json:"deletionPolicy,omitempty"`

	// AWS tags to apply to the registry resource.
	Tags map[string]*string `json:"tags,omitempty"`
}

// Registry_SDK_Status defines the observed state of Registry
type Registry_SDK_Status struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`

	// The Amazon Resource Name (ARN) of the registry.
	// +kubebuilder:validation:Optional
	RegistryARN *string `json:"registryARN,omitempty"`

	// The current compatibility mode setting for the registry.
	// This reflects the actual state in AWS and may differ from spec.compatibility
	// if an update is in progress or if there was an error applying the change.
	// +kubebuilder:validation:Optional
	Compatibility *string `json:"compatibility,omitempty"`

	// The number of schemas that are currently using this registry.
	// This count is used to enforce referential integrity - a registry with
	// dependent schemas cannot be deleted until the schemas are removed or
	// reassigned to a different registry.
	// +kubebuilder:validation:Optional
	DependentSchemaCount *int64 `json:"dependentSchemaCount,omitempty"`
}

// Registry is the Schema for the Registries API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ARN",type=string,JSONPath=`.status.registryARN`
// +kubebuilder:printcolumn:name="COMPATIBILITY",type=string,JSONPath=`.spec.compatibility`
// +kubebuilder:printcolumn:name="SCHEMAS",type=integer,JSONPath=`.status.dependentSchemaCount`
// +kubebuilder:printcolumn:name="SYNCED",type=string,JSONPath=`.status.conditions[?(@.type=="ACK.ResourceSynced")].status`
// +kubebuilder:printcolumn:name="AGE",type=date,JSONPath=`.metadata.creationTimestamp`
type Registry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RegistrySpec        `json:"spec,omitempty"`
	Status            Registry_SDK_Status `json:"status,omitempty"`
}

// RegistryList contains a list of Registry
// +kubebuilder:object:root=true
type RegistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Registry `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Registry{}, &RegistryList{})
}
