// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SchemaSpec defines the desired state of Schema.
//
// Represents an AWS Glue Schema with embedded version management.
// Schema versions are automatically managed by AWS Glue when the
// schema definition is updated.
type SchemaSpec struct {

	// The name of the schema. This is a unique identifier for the schema
	// within its registry.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	SchemaName *string `json:"schemaName"`

	// The schema definition in the format specified by dataFormat.
	// When this field is updated, a new schema version will be created
	// in AWS Glue (subject to compatibility validation).
	// +kubebuilder:validation:Required
	SchemaDefinition *string `json:"schemaDefinition"`

	// The data format of the schema definition.
	// Valid values are:
	//   - AVRO: Apache Avro schema format
	//   - JSON: JSON Schema format
	//   - PROTOBUF: Protocol Buffers schema format
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=AVRO;JSON;PROTOBUF
	DataFormat *string `json:"dataFormat"`

	// Reference to a Registry CRD in the same namespace.
	// If not specified, the schema will be created in the default AWS Glue registry.
	// +kubebuilder:validation:Optional
	RegistryRef *RegistryReference `json:"registryRef,omitempty"`

	// A description of the schema. If description is not provided, there will
	// not be any default value for this string.
	// +kubebuilder:validation:MaxLength=2048
	Description *string `json:"description,omitempty"`

	// The compatibility mode for schema evolution.
	// If specified, this overrides the compatibility mode set at the registry level.
	// Valid values are the same as Registry.Spec.Compatibility.
	// +kubebuilder:validation:Enum=NONE;DISABLED;BACKWARD;FORWARD;FULL;BACKWARD_ALL;FORWARD_ALL;FULL_ALL
	Compatibility *string `json:"compatibility,omitempty"`

	// Determines whether the AWS resource is deleted when the Schema CRD is deleted.
	// Valid values are:
	//   - Delete: The AWS Glue Schema will be deleted when the CRD is deleted
	//   - Retain: The AWS Glue Schema will be retained when the CRD is deleted
	// +kubebuilder:validation:Enum=Delete;Retain
	// +kubebuilder:default=Delete
	DeletionPolicy *string `json:"deletionPolicy,omitempty"`

	// AWS tags to apply to the schema resource.
	Tags map[string]*string `json:"tags,omitempty"`
}

// RegistryReference links a Schema to a Registry CRD.
// This enables Kubernetes-native referential integrity checking.
type RegistryReference struct {
	// Name of the Registry CRD in the same namespace as this Schema.
	// The referenced Registry must exist before the Schema can be created.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
}

// Schema_SDK_Status defines the observed state of Schema
type Schema_SDK_Status struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`

	// The Amazon Resource Name (ARN) of the schema.
	// +kubebuilder:validation:Optional
	SchemaARN *string `json:"schemaARN,omitempty"`

	// Metadata about the latest version of the schema.
	// This is updated whenever a new version is created in AWS Glue.
	// +kubebuilder:validation:Optional
	LatestVersion *SchemaVersionMetadata `json:"latestVersion,omitempty"`

	// The ARN of the registry this schema belongs to.
	// This is resolved from RegistryRef (if specified) or is the default registry ARN.
	// +kubebuilder:validation:Optional
	RegistryARN *string `json:"registryARN,omitempty"`
}

// SchemaVersionMetadata contains information about a specific version of a schema.
// AWS Glue automatically increments version numbers when compatible updates are made.
type SchemaVersionMetadata struct {
	// The version number auto-assigned by AWS Glue.
	// Versions start at 1 and increment with each compatible schema update.
	// +kubebuilder:validation:Optional
	VersionNumber *int64 `json:"versionNumber,omitempty"`

	// The unique identifier assigned by AWS Glue to this schema version.
	// +kubebuilder:validation:Optional
	SchemaVersionID *string `json:"schemaVersionID,omitempty"`

	// The status of this schema version.
	// Valid values are:
	//   - AVAILABLE: The version is ready for use
	//   - PENDING: The version is being created
	//   - DELETING: The version is being deleted
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`

	// The timestamp when this version was created in AWS Glue.
	// +kubebuilder:validation:Optional
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
}

// Schema is the Schema for the Schemas API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ARN",type=string,JSONPath=`.status.schemaARN`
// +kubebuilder:printcolumn:name="VERSION",type=integer,JSONPath=`.status.latestVersion.versionNumber`
// +kubebuilder:printcolumn:name="FORMAT",type=string,JSONPath=`.spec.dataFormat`
// +kubebuilder:printcolumn:name="REGISTRY",type=string,JSONPath=`.spec.registryRef.name`
// +kubebuilder:printcolumn:name="SYNCED",type=string,JSONPath=`.status.conditions[?(@.type=="ACK.ResourceSynced")].status`
// +kubebuilder:printcolumn:name="AGE",type=date,JSONPath=`.metadata.creationTimestamp`
type Schema struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SchemaSpec        `json:"spec,omitempty"`
	Status            Schema_SDK_Status `json:"status,omitempty"`
}

// SchemaList contains a list of Schema
// +kubebuilder:object:root=true
type SchemaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Schema `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Schema{}, &SchemaList{})
}
