// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TableSpec defines the desired state of Table.
//
// The database and table in the Glue Data Catalog that is used for input or
// output data.
type TableSpec struct {

	// The ID of the Data Catalog in which to create the Table. If none is supplied,
	// the Amazon Web Services account ID is used by default.
	//
	// Regex Pattern: `^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	CatalogID *string `json:"catalogID,omitempty"`
	// The catalog database in which to create the new table. For Hive compatibility,
	// this name is entirely lowercase.
	//
	// Regex Pattern: `^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	DatabaseName *string                                  `json:"databaseName,omitempty"`
	DatabaseRef  *ackv1alpha1.AWSResourceReferenceWrapper `json:"databaseRef,omitempty"`
	// A description of the table.
	//
	// Regex Pattern: `^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*$`
	Description *string `json:"description,omitempty"`
	// The table name. For Hive compatibility, this is folded to lowercase when
	// it is stored.
	//
	// Regex Pattern: `^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The table owner. Included for Apache Hive compatibility. Not used in the
	// normal course of Glue operations.
	//
	// Regex Pattern: `^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$`
	Owner *string `json:"owner,omitempty"`
	// These key-value pairs define properties associated with the table.
	Parameters map[string]*string `json:"parameters,omitempty"`
	// A list of columns by which the table is partitioned. Only primitive types
	// are supported as partition keys.
	//
	// When you create a table used by Amazon Athena, and you do not specify any
	// partitionKeys, you must at least set the value of partitionKeys to an empty
	// list. For example:
	//
	// "PartitionKeys": []
	PartitionKeys []*Column `json:"partitionKeys,omitempty"`
	// The retention time for this table.
	Retention *int64 `json:"retention,omitempty"`
	// A storage descriptor containing information about the physical storage of
	// this table.
	StorageDescriptor *StorageDescriptor `json:"storageDescriptor,omitempty"`
	// The type of this table. Glue will create tables with the EXTERNAL_TABLE type.
	// Other services, such as Athena, may create tables with additional table types.
	//
	// Glue related table types:
	//
	// EXTERNAL_TABLE
	//
	// Hive compatible attribute - indicates a non-Hive managed table.
	//
	// GOVERNED
	//
	// Used by Lake Formation. The Glue Data Catalog understands GOVERNED.
	TableType *string `json:"tableType,omitempty"`
	// A TableIdentifier structure that describes a target table for resource linking.
	TargetTable *TableIdentifier `json:"targetTable,omitempty"`
	// Included for Apache Hive compatibility. Not used in the normal course of
	// Glue operations.
	ViewExpandedText *string `json:"viewExpandedText,omitempty"`
	// Included for Apache Hive compatibility. Not used in the normal course of
	// Glue operations. If the table is a VIRTUAL_VIEW, certain Athena configuration
	// encoded in base64.
	ViewOriginalText *string `json:"viewOriginalText,omitempty"`
}

// TableStatus defines the observed state of Table
type TableStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// Table is the Schema for the Tables API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Table struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TableSpec   `json:"spec,omitempty"`
	Status            TableStatus `json:"status,omitempty"`
}

// TableList contains a list of Table
// +kubebuilder:object:root=true
type TableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Table `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Table{}, &TableList{})
}
